app/manifest.json
=> add gist url in manifest

README.md
=> update readme, minor typo

CONTRIBUTING.md
Addresses https://github.com/OctoLinker/browser-extension/issues/86#issuecomment-222381365:
>  - [ ] Example commit which show of a plugin being added.
=> List example plugin commits in CONTRIBUTING.md

assets/style.css, lib/insert-link.js, test/insert-link.test.js
This allows the links to be "clicked" with [Vimium].
[Vimium]: https://vimium.github.io/
(cherry-picked from commit 0a69feedd80a39197b9cf7aa0b9bdf88eee56892)
=> Insert <a> (no href) instead of <span>

lib/resolver/javascript-universal.js, test/resolver/javascript-universal.test.js
See https://github.com/OctoLinker/browser-extension/pull/95#issuecomment-229799358
=> Correctly resolve targets like @angular/core/bar.js

package.json
I'm hoping this will fix the intermittent error described in https://github.com/OctoLinker/browser-extension/pull/115#issuecomment-229819535
=> Upgrade testing libraries

package.json
See https://github.com/OctoLinker/browser-extension/issues/135
@stefanbuck, as we've discussed privately, I'll take a shot at doing the releases for this one. Just to confirm, here are the steps that are needed (as far as I know):
=> Release 4.2.0

README.md
@josephfrazier this PR adds a list of all features that we have in the OctoLinker. I'm not sure if we have to explain every single feature in detail, because it's basically always the same. What do you think?
=> List features 

assets/manifest.json, npm-shrinkwrap.json, package.json
=> Release 4.3.0

lib/click-handler.js, test/click-handler.test.js
Finally, it's possible to open links in a new tab on middle mouse click 🎉
=> Opening links in new tab on middle mouse click

assets/manifest.json, assets/options.html
This PR adds a simple options page which works on all supported browsers. As a minimal value for the user I added a github button.
=> Add option page

CONTRIBUTING.md
See https://github.com/OctoLinker/browser-extension/issues/86#issuecomment-254149180
The commits were found with this command:
git log --oneline ea30b42684cf60d65118562c7ffdcc267067517e... ./lib/plugins
=> Update plugin links in CONTRIBUTING.md

lib/resolver/javascript-universal.js, lib/utils/builtins-docs.js, test/resolver/javascript-universal.test.js
Example: https://github.com/kittens/roadrunner/blob/2ead9501e3681fa7584b79e6e6546fb046a83f54/index.js#L3
=> Resolve require('module') to https://nodejs.org/api/modules.html

packages/blob-reader/fixtures/github.com/pull/comments.html, packages/blob-reader/helper.js, packages/blob-reader/test.js
While fixing #184 I added support for resolving links in PR comments 😄
=> Resolve links in PullRequest comments

packages/blob-reader/fixtures/github.com/blob/89f13651df126efdb4f1e3ae40183c9fdccdb4d3.html, packages/blob-reader/fixtures/github.com/pull/diff.html, packages/blob-reader/helper.js, packages/blob-reader/test.js
Looks like the HTML has slightly changed and no one has noticed it. We should run the test also against https://github.com/OctoLinker/testrepo/ to verify that our fixtures are up to dates. Will take a look on this.
=> Fix bug where blob path in pr diff was undefined

.travis.yml, packages/blob-reader/fixtures/github.com/blob/89f13651df126efdb4f1e3ae40183c9fdccdb4d3.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_split.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_unified.html, packages/blob-reader/fixtures/github.com/gist/113827963013e98c6196db51cd889c39.html, packages/blob-reader/fixtures/github.com/pull/comments.html, packages/blob-reader/fixtures/github.com/pull/diff.html, packages/blob-reader/scripts/update-fixtures.sh, packages/blob-reader/test.js
This PR updates the fixtures with their latest version. Also I added a script to fetch them easily. Finally, on travis the update script runs upfront to ensure we test the latest html version. We still keep a version of the fixtures in the repo for the record.
=> Update blob reader fixtures

lib/background.js
@josephfrazier before merging this, please read the my message that I sent you on twitter 😉
=> Update GA tracking code

lib/debug-mode.js
in order to match with the css declaration
=> Fix debug class name

.eslintrc, npm-shrinkwrap.json, package.json, packages/blob-reader/test.js, test/insert-link.test.js
Added [eslint-plugin-mocha](https://github.com/lo1tuma/eslint-plugin-mocha), because I already pushed twice `describe.only` 😊
=> Add eslint-plugin-mocha

.github/issue_template.md
This should make it easier and faster to track down bugs as they are
reported, by asking for relevant details in advance.
See the following links for more details about issue templates:
* https://github.com/blog/2111-issue-and-pull-request-templates
* https://help.github.com/articles/creating-an-issue-template-for-your-repository/
=> Add a GitHub issue template

packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js
=> Update `REQUIRE` regex to allow whitespaces around quotes

lib/plugins/bower-manifest.js, lib/plugins/javascript.js, lib/plugins/npm-manifest.js
Fixes https://github.com/OctoLinker/browser-extension/issues/298
=> npm, bower: ensure file paths resolve to files

lib/plugins/javascript.js, package.json, test/plugins/javascript.test.js, yarn.lock
Fixes https://github.com/OctoLinker/browser-extension/issues/300
=> javascriptFile: fallback from ./dist to ./lib to ./src

CONTRIBUTING.md, lib/background/newTab.js, lib/click-handler.js, lib/options/options.js, lib/pattern-preset.js, lib/plugins/css.js, packages/blob-reader/fixtures/github.com/issue/code.html, packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js
=> Add css import support

lib/notification.js, lib/options/options.js
This PR allows users to turn off the update notification.
=> Add option to turn off update notification

CONTRIBUTING.md
This makes them a little more human-friendly and fixes the rendering of the nested lists. Compare the "Build and load the extension" items between this commit and [master](https://github.com/OctoLinker/browser-extension/blob/9fe6a165f418e153bc6e20964d26238548f89664/CONTRIBUTING.md#quick-start).
EDIT: Here's the "rich diff" showing the rendered difference: https://github.com/OctoLinker/browser-extension/pull/319/files?short_path=6a33714#diff-6a3371457528722a734f3c51d9238c13
=> CONTRIBUTING.md: Use 1-indexing in lists

.hound.yml
For more details visit https://houndci.com/
=> Enabled houndci

README.md
=> Fix the title formatting in README

lib/pattern-preset.js, lib/plugins/requirements-txt.js, packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js
Specification: https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format
Test page: https://github.com/bndr/pipreqs/blob/1a990b52d5e1d24cd5a2e7673077ff48ae52f9d3/requirements.txt
Fixes https://github.com/OctoLinker/browser-extension/issues/331
=> Add requirements.txt plugin

packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js
Test page: https://github.com/nvbn/thefuck/blob/d28567bb313d5b925306d72417523985af41deb6/requirements.txt#L2
=> requirements.txt plugin: match packages without version specifier

lib/plugins/bower-manifest.js
Test page: https://github.com/velesin/jasmine-jquery/blob/df93bcf015fc0a541374fb5dd1e60782b1f34a69/bower.json#L12-L13
=> bower: Remove unused/missing variable

.hound.yml
See https://github.com/OctoLinker/browser-extension/pull/321#issuecomment-292153699
=> Remove .hound.yml

lib/plugins/javascript.js, test/plugins/javascript.test.js
Fixes https://github.com/OctoLinker/browser-extension/issues/352
=> javascript: Add .ls (LiveScript) to possible extensions

packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js
Fixes https://github.com/OctoLinker/browser-extension/issues/360
=> Link `proxyquire` like `require`

CONTRIBUTING.md
See https://github.com/OctoLinker/browser-extension/pull/362#issuecomment-304760592
=> CONTRIBUTING.md: Note that new features should be documented

README.md, lib/plugins/nodejs-relative-path.js, packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js, test/plugins/nodejs-relative-path.test.js
Fixes https://github.com/OctoLinker/browser-extension/issues/359
Demos:
* https://github.com/pegjs/website/blob/5924ede36795192b77f2cb9bfe25a56e8e8b6f90/app.js#L12
* https://github.com/antoninlanglade/totopack/blob/055a725660a11d9c765434198edc7bb538ec5ccf/config/paths.js#L6
=> Resolve `__dirname + '/some/relative/path'`

README.md, lib/plugins/dot-net-core.js, lib/plugins/dot-net.js, lib/plugins/helper/regex-builder.js, lib/resolver/nuget.js, packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js, test/plugins/dot-net.test.js
Here is an example of packages.config:
https://github.com/olsh/resharper-configuration-sense/blob/master/src/Resharper.ConfigurationSense/packages.config
=> Add support for .NET Framework packages.config

packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js
=> Change rust regex to be more exclusive

assets/manifest.json, package.json
---
HTML script tag support and a few other improvements
__Before we dive into the changes a comment on our own behalf:__
> OctoLinker is a tool made by software developers for software developers with passion and love for what we do. If you like what we're doing, and appreciate our many of hours spent on OctoLinker, please consider [backing](https://opencollective.com/octolinker#backers) or [sponsoring](https://opencollective.com/octolinker#sponsors) OctoLinker's open source collective. 
>
> Especially if you use OctoLinker for **your daily business needs**, please consider our [company](https://opencollective.com/octolinker#company) option.
>
> _Thank you_
- Handle HTML script tags #383
- Add support for `golang.org` imports #381 
- Support commit-ish in package.json #375
- Change rust …
=> Release v4.13.0

packages/blob-reader/fixtures/github.com/blob/89f13651df126efdb4f1e3ae40183c9fdccdb4d3.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_split.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_unified.html, packages/blob-reader/fixtures/github.com/gist/113827963013e98c6196db51cd889c39.html, packages/blob-reader/fixtures/github.com/issue/code.html, packages/blob-reader/fixtures/github.com/pull/comments.html, packages/blob-reader/fixtures/github.com/pull/diff.html, packages/blob-reader/test.js
I don't know how this can happen, but the hash for this file changed. 
Edit:  I remember I addressed the same issue a few weeks ago. Reverting the old commit seems to fix this.
=> Update git hash to fix tests

lib/octo-linker.js
This was introduced in #415 and is the root cause of the build error in #418.
=> Fix load plugins error

package.json, packages/helper-grammar-regex-collection/regex.js, yarn.lock
It was published in v4.0.0: https://github.com/slevithan/xregexp/pull/205
=> Use XRegExp.tag instead of re-implementing it

__mocks__/path.js, lib/plugins/go.js, lib/plugins/javascript.js, lib/plugins/nodejs-relative-path.js, lib/plugins/ruby.js, lib/plugins/sass.js, lib/resolver/relative-file.js, test/_setup.js
Let's use the good old `path.join` and mock `join` to make the tests working on windows.
=> Move away from posix

CONTRIBUTING.md, README.md, lib/notification.js, package.json, scripts/chrome-launch.js
=> Update repo references

README.md, privacy-policy.md
This document describes what data we collect and why.
=> Add privacy policy

packages/helper-insert-link/index.js, yarn.lock
=> Bump dependencies

packages/plugin-javascript/__tests__/__snapshots__/index.js.snap, packages/plugin-javascript/__tests__/index.js
I think snapshot testing makes a lot of sense in this area.
=> Jestify javascript plugin tests

.appveyor.yml, .travis.yml
See https://github.com/OctoLinker/OctoLinker/pull/474#issuecomment-397871950
=> Use Node 10 on Travis and Appveyor

e2e/README.md
As requested in https://github.com/OctoLinker/OctoLinker/pull/477#issuecomment-406057799
I also think we should change the "How do we know" heading, but I'm not sure what to change it to. @stefanbuck, could you explain the concept you're trying to write? Thanks!
=> Update E2E readme grammar

packages/blob-reader/__snapshots__/test.js.snap, packages/blob-reader/fixtures/github.com/blob/89f13651df126efdb4f1e3ae40183c9fdccdb4d3.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_split.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_unified.html, packages/blob-reader/fixtures/github.com/gist/113827963013e98c6196db51cd889c39.html, packages/blob-reader/fixtures/github.com/issue/code.html, packages/blob-reader/fixtures/github.com/pull/comments.html, packages/blob-reader/fixtures/github.com/pull/diff.html, packages/blob-reader/test.js
GitHub changed the way how they insert `-` and `+` signs in a diff view from inline text to a css pseudo element. I took this opportunity and converted all blob test to jest.
=> Fix blob tests

.gitignore, .travis.yml, jest.config.js, package.json, yarn.lock
Note: I branched off from #489 to get a working build
Configure this project to report code coverage using codecov https://codecov.io/gh/OctoLinker/OctoLinker
=> Add Codecov

packages/blob-reader/test.js
See https://github.com/OctoLinker/OctoLinker/pull/508#issuecomment-417105916
=> Skip failing test for now

scripts/chrome-launch.js
Fixes #507, unsure if you want to keep these *-open around, but in Windows the relative dir is not resolved.
=> Fix yarn chrome-open to run in Windows

e2e/fixtures/javascript/npm/package.json
Fix vulnerability warning for lodash even this is just a dummy package.json file.
=> Fix vulnerability warning for lodash

assets/manifest.json, assets/options.html, packages/helper-settings/SettingsForm.js, packages/helper-settings/components/index.js, packages/helper-settings/components/input.js, packages/helper-settings/package.json, packages/helper-settings/page.js
This Pull Request improves the settings page by providing feedback if the entered token is valid or not.
=> Refine settings page

package.json, packages/helper-github-api/__tests__/fetch-tree.js, packages/helper-github-api/fetch-tree.js, packages/helper-github-api/index.js, packages/helper-github-api/package.json, yarn.lock
Another PR along the way to refactor OctoLinker to the next major version. Soon we will use this package to resolve relative files using the github tree api https://developer.github.com/v3/git/trees/
=> Add helper-github-api package

packages/core/background/index.js, packages/core/click-handler.js, packages/core/utils/fetch.js
Chrome 73 changed to cross-origin requests in chrome extension content scripts see
https://www.chromestatus.com/feature/5629709824032768
Fix #545
=> Fetch links in background script

e2e/fixtures/java/rough-snowflake.java, packages/plugin-java/__tests__/index.js, packages/plugin-java/index.js
Counter part for https://github.com/OctoLinker/api/pull/99
=> Resolve all Java dependencies through OctoLinker API

e2e/fixtures/go/foo.go, packages/helper-normalise-resolver-results/__snapshots__/test.js.snap, packages/helper-normalise-resolver-results/index.js, packages/helper-normalise-resolver-results/test.js
Use ping resolver when plugin returns more than one url
=> Use ping resolver when plugin returns more than one url

packages/plugin-javascript/package.json
Reverts OctoLinker/OctoLinker#592
=> Revert "Bump builtins from 1.0.3 to 2.0.1"

packages/helper-settings/package.json
Reverts OctoLinker/OctoLinker#669
=> Revert "Bump webextension-polyfill from 0.4.0 to 0.5.0"

packages/blob-reader/fixtures/github.com/blob/89f13651df126efdb4f1e3ae40183c9fdccdb4d3.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_split.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_unified.html, packages/blob-reader/fixtures/github.com/gist/113827963013e98c6196db51cd889c39.html, packages/blob-reader/fixtures/github.com/issue/code.html, packages/blob-reader/fixtures/github.com/pull/comments.html, packages/blob-reader/fixtures/github.com/pull/diff.html, packages/blob-reader/test.js
=> Re-enable diff view tests

e2e/fixtures/.github/workflows/ci.yml, packages/core/load-plugins.js, packages/core/package.json, packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js, packages/plugin-github-actions/__tests__/index.js, packages/plugin-github-actions/index.js, packages/plugin-github-actions/package.json
=> Add GitHub Action support

CONTRIBUTING.md, package-lock.json, package.json, webpack.config.js
Finally, enable auto reload by using [webpack-extension-reloader](https://github.com/rubenspgcavalcante/webpack-extension-reloader/) 😍
=> Add webpack-extension-reloader

packages/helper-insert-link/__tests__/__snapshots__/get-position.js.snap, packages/helper-insert-link/__tests__/get-position.js, packages/helper-insert-link/get-position.js
The original implementation was using 0 as first line number, but for clarity it should start with 1.
=> The line number should start at 1

e2e/fixtures/ruby/mystic-wind.rb
Found a few issue with some require statements #773
=> Increase E2E coverage for Ruby

README.md, e2e/README.md, e2e/fixtures/dotnet/ClassicProject.csproj, e2e/fixtures/dotnet/Directory.Build.props, e2e/fixtures/dotnet/Directory.Build.targets, e2e/fixtures/dotnet/SdkProject.csproj, packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js, packages/plugin-dot-net/index.js
Here's a list of files that can be used to verify these changes:
- https://github.com/SixLabors/ImageSharp.Web/blob/4a49f4d5c582d66dde963aa3eb5d88bdd5313491/src/ImageSharp.Web/ImageSharp.Web.csproj#L14-L30
- https://github.com/SixLabors/ImageSharp.Web/blob/4a49f4d5c582d66dde963aa3eb5d88bdd5313491/Directory.Build.props#L99-L105
- https://github.com/SixLabors/ImageSharp.Web/blob/4a49f4d5c582d66dde963aa3eb5d88bdd5313491/Directory.Build.targets#L19-L42
-
Closes #784
=> Expand .net/nuget support for .targets files and FrameworkReferences

packages/plugin-dot-net-project/__tests__/index.js
I forgot to commit this as part of #789 😞
=> Add tests for plugin-dot-net-project

e2e/fixtures/rust/Cargo.toml, package-lock.json, packages/core/load-plugins.js, packages/core/package.json, packages/helper-regex-builder/index.js, packages/plugin-rust-cargo/index.js, packages/plugin-rust-cargo/package.json
Here's a rough pass and trying to add in Cargo.toml support as requested in #857. This was more of an exercise in trying to better understand how things work but I'm sure it can be cleaned up and used.
=> Support for cargo.toml files

packages/core/app.js, packages/core/update-notice.js
=> Add upcoming permission notification

packages/helper-grammar-regex-collection/go.js, packages/helper-grammar-regex-collection/test.js, packages/plugin-go/index.js
Original authored by @StarpTech. Dude to some issues with our E2E tests, I had to raise this Pull Request myself.
This Pull Request provides initial support for https://golang.org/cmd/go/#hdr-The_go_mod_file
Tested with: https://github.com/mattermost/mattermost-server/blob/master/go.mod
In favour of #845 which fixes #554
=> Add gmod support

e2e/fixtures/javascript/index.svelte, e2e/fixtures/javascript/relative/proud-tooth.svelte, packages/plugin-javascript/index.js
Sample file: https://github.com/hankxdev/one-click-extensions-manager/blob/918841cbdbca86a88498595e660c122c7cef576b/source/App.svelte
Closes #897
=> Add support for .svelte files

README.md
[ZEIT has been renamed to Vercel in April.](https://vercel.com/blog/zeit-is-now-vercel) Let's update the README accordingly :)
=> Change ZEIT to Vercel in README

e2e/fixtures/.github/workflows/ci.yml, packages/plugin-docker/index.js, packages/plugin-github-actions/index.js, packages/plugin-github-actions/package.json
- [.github/workflows/cypress-report.yml#L18](https://github.com/makwanaparth94/CypressTest-GithubActions/blob/57e3fb2b91a992a2ed58b750dd37703cded18b9e/.github/workflows/cypress-report.yml#L18)
- [.github/workflows/ci.yml#L81](https://github.com/WyriHaximusNet/docker-php/blob/67a3785d080b41c897c93ea32fec72c89de48fa6/.github/workflows/ci.yml#L81)
- [.github/workflows/testing.yml#L11](https://github.com/oidcphp/support/blob/4a416eb990655dbf25389bf5fd1fb9b362adc4a5/.github/workflows/testing.yml#L11)
The docs for this can be found at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-a-docker-hub-action
=> Add support for docker hub actions

e2e/fixtures/dotnet/paket.dependencies, packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js
Docs: https://fsprojects.github.io/Paket/nuget-dependencies.html#Special-case-CLI-tools
Example: [paket.dependencies#L18](
https://github.com/fsprojects/FSharp.Azure.Storage/blob/7a70e82161f0cc8cda6e38b95f842d30a071d07a/paket.dependencies#L18)
=> Support cli tools in Paket

e2e/README.md, package.json, scripts/chrome-launch.js
=> Use main branch in dev urls

package.json, yarn.lock
=> Remove unused codecov dependency

e2e/automated.test.js, e2e/fixtures/.github/CODEOWNERS
=> Add resolve checks to codeowners tests

e2e/fixtures/r/foo.R, packages/blob-reader/fixtures/github.com/issue/code.html, packages/core/load-plugins.js, packages/helper-grammar-regex-collection/index.js, packages/helper-grammar-regex-collection/test.js, packages/plugin-r/index.js, packages/plugin-r/package.json
I'm still puzzling through the regex handling for R manifests, which may make sense to handle via a separate plugin, as with Ruby or Rust, but this covers scripts and RMarkdown files.
=> Rstats library

.github/workflows/ci.yml, packages/helper-process-json/index.js, packages/helper-process-json/package.json, yarn.lock
This package [changed it's name](https://github.com/JSONPath-Plus/JSONPath/blob/master/CHANGES.md#0120-dec-12-2015-1039pm) years ago which is why we haven't received any updates for it. There shouldn't be any changes between these two versions exception for the name change. Should I try updating to a newer version or should be a different PR?
=> Update package name from JSONPath to jsonpath-plus and update to the latest version

packages/plugin-go/index.js, packages/plugin-javascript/index.js, packages/plugin-ruby/index.js
[![](https://github.com/OctoLinker/OctoLinker/workflows/Node%20CI/badge.svg?branch=use-relative-file)](https://github.com/OctoLinker/OctoLinker/pull/1052/checks) [![Pull Request Badge](https://badgen.net/badge/Generated%20by/Pull%20Request%20Badge/purple)](https://pullrequestbadge.com/?rel=badge)
This PR is aimed to close #796. From the issue, "OctoLinker/packages/plugin-nodejs-relative-path/index.js" has already been fixed from another PR. So this one is finishing the remaining files. Thanks
=> Refactor code to use relativeFile function from resolver-relative-file package

e2e/fixtures/rust/Cargo.toml
=> Update repo url for env_logger

scripts/version.sh
Update Safari version when running `npm version` as outlined in https://github.com/OctoLinker/OctoLinker/pull/1167#discussion_r553619566
=> Update Safari version when using npm version script

e2e/fixtures/rust/Cargo.toml, packages/helper-settings/SettingsForm.js, packages/helper-settings/index.js, packages/plugin-php/__tests__/index.js, packages/plugin-php/index.js, packages/plugin-php/package.json, packages/resolver-hoogle-search/__tests__/index.js, packages/resolver-hoogle-search/index.js
=> Remove php feature flag

e2e/fixtures/go/foo.go, e2e/fixtures/java/rough-snowflake.java
The target url of a few dependencies changed and this PR is updating the fixtures file so the CI turns green again
=> Update failing End 2 End tests with new target url

e2e/fixtures/solidity/foo.sol, e2e/fixtures/solidity/import.sol, packages/blob-reader/fixtures/github.com/issue/code.html, packages/core/load-plugins.js, packages/core/package.json, packages/helper-grammar-regex-collection/index.js, packages/plugin-solidity/__tests__/index.js, packages/plugin-solidity/index.js, packages/plugin-solidity/package.json
Adds support for Solidity's `import` statement.
See [this solidity file](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol) as an example.
You should be able to click `"./IERC721.sol"` within `import "./IERC721.sol";` and see that file.
=> Add Solidity plugin

.github/workflows/ci.yml, packages/blob-reader/fixtures/github.com/blob/89f13651df126efdb4f1e3ae40183c9fdccdb4d3.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_split.html, packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_unified.html, packages/blob-reader/fixtures/github.com/gist/cbc01d87dca84a6e0b118b73a2d49927.html, packages/blob-reader/fixtures/github.com/issue/code.html, packages/blob-reader/fixtures/github.com/pull/comments.html, packages/blob-reader/fixtures/github.com/pull/diff.html, packages/blob-reader/helper.js
GitHub made some changes to the DOM which caused OctoLinker to not function well in some scenarios like in a diff view. See comments for full disclosure
=> Fix blob reader

.github/workflows/dependabot-auto-merge.yml
A few weeks ago we set up auto merge for dependabot PRs but this is not working as intended. 
@xt0rted found a really smart solution that does not require using a PAT (personal access token). Check out his gist to learn more.
https://gist.github.com/xt0rted/46475099dc0a70ba63e16e3177407872
=> Auto merge Dependabot PRs

packages/core/plugin-manager.js
Found this while working on #1475. From what I can tell nothing depends on this code.
=> Remove unused code

.github/workflows/release.yml, assets/manifest.json, package.json, packages/core/package.json, scripts/version.sh
A discussed with @xt0rted this updates thee release flow. Now it is just a matter of creating a release.
=> New release flow

.editorconfig
Looks like I missed this in #1454.
=> Ensure .sh files use LF line endings

e2e/fixtures/rust/Cargo.toml
This project moved orgs which is why the test is failing.
=> Update test url
