- DEVELOPER.md
Before, they were leading me to 404s like https://github.com/OctoLinker/browser-extension/blob/master/blob/master/lib/plugins (note the extra "/blob/master")
> Fix intra-repo links in DEVELOPER.md

- lib/gh-interface.js
The problem was this native function [insertAdjacentHTML](https://github.com/OctoLinker/browser-extension/blob/b0bdcd077016d0ddf828e28f61b1404583c47f0c/lib/gh-interface.js#L30) which seems to be not available in PhantomJS.
> Use jQuery to make tests working in PhantomJs

- lib/plugins/javascript/index.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
The module spec allows for the following:
```js
export * from "foo";
export {foo, bar} from "foo";
export {foo as bar} from "foo";
```
Reference:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#Syntax
- http://www.ecma-international.org/ecma-262/6.0/#sec-exports
Fixes #78
> Allow for exported imports.

- lib/insert-link.js
- test/insert-link.test.js
This allows you to specify place holders in the data-attr object. These place holders are replaced with the associated match from the RegExp.
```js
insertLink(blob.el, HOMEBREW, {
resolver: 'relativeFile',
path: blob.path,
target: '$1.rb',
});
```
> Template strings in data attr object

- lib/click-handler.js
Happy Memorial Day!
This is related to item #88 
Using `currentTarget` in the click handler over `target` ensures that even if [other extensions](https://github.com/Nuclides/github-highlight-selected) change the DOM, we still get what we want.
> Use currentTarget for click handler event.

- package.json
This lets you `npm install` multiple times without issue.
(from https://github.com/OctoLinker/browser-extension/pull/97#issuecomment-225069078)
> postinstall: overwrite pre-commit hook if needed

- lib/load-plugins.js
- lib/octo-linker.js
- test/load-plugins.test.js
Based on the feedback from @josephfrazier in https://github.com/OctoLinker/browser-extension/issues/86, this PR adds an auto-loader which loads all plugins located in `lib/plugins`. By that, a plugin developer doesn't have to think about import the plugin manually.
> Plugins located in lib/plugins will be auto-loaded

- .travis.yml
Every time when a new git tag is pushed to master travis will automatically build and upload the browser builds to the corresponding git tag on the release page
> Upload builds to GitHub releage page

- .travis.yml
Travis already tests Node v4 at the latest minor/patch version.
> Don't test Node v4.0 on Travis

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
This is only for `cask:` dependencies/conflicts. Here's an example:
https://github.com/caskroom/homebrew-cask/blob/d58e2c0724fe782a4ba18383e3dc387c59d63567/Casks/lazarus.rb#L11
> Support Homebrew-Cask dependencies/conflicts

- lib/plugins/npm-manifest/index.js
Example: https://github.com/substack/node-browserify/blob/071642ad9cbb44cb530d43edfac17c5077a9442c/package.json#L7
Spec: https://docs.npmjs.com/files/package.json#bin
> Link the `bin` field in package.json

- lib/plugins/npm-manifest/index.js
Example: https://github.com/matthew-andrews/isomorphic-fetch/blob/89c7e70c313d4965f05ac8f0f3a2fcf239c82876/package.json#L5
Spec: https://github.com/defunctzombie/package-browser-field-spec#spec
> Link the `browser` field in package.json

- .travis.yml
This should reduce build times by about half, since `npm install` won't
need to install anything most of the time. Here are some log lines
showing how long `npm install` currently takes:
https://travis-ci.org/OctoLinker/browser-extension/jobs/144849130#L147
https://travis-ci.org/OctoLinker/browser-extension/jobs/144849129#L147
Here is the Travis documentation about the cache feature:
https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
> Travis: cache node_modules across builds

- .gitattributes
The stats report for the repository aren't correct, because of the massiv fixtures files for the blob reader. To fix this, I added an entry to `.gitattributes` to remove thoese files from the stats. For more details go to https://github.com/github/linguist#overrides
> Remove HTML files from GH stats

- lib/insert-link.js
- lib/plugins/typescript/index.js
- lib/resolver/javascript-file.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- test/insert-link.test.js
This PR adds support for TypeScript `import` and `require` statements. Also it allows to click on the path specified in a ts reference tag see #67.
In order to make this happen I had to tweak the `insert-link`, because the html structure for ts files is a bit different than for javascript. 
@josephfrazier  can you also do a quick sanity check with some TS project, please. That would be great.
> Add Typescript support

- package.json
`npm version` is an easy way to commit a new version, but it only
updates `package.json`. This script ensures that the version in
`assets/manifest.json` is kept in sync, to avoid a reoccurrence of
https://github.com/OctoLinker/browser-extension/pull/136#issuecomment-236394248
See here for details about `npm version` and its associated package.json
scripts: https://docs.npmjs.com/cli/version
> Upon `npm version`: update assets/manifest.json

- assets/manifest.json
This was done with `npm run version`, which normally happens as part of
`npm version` (see https://github.com/OctoLinker/browser-extension/pull/137)
It looks like the `json` command reformatted a couple of other fields,
but that should be a one-time thing, assuming we preserve the new
formatting with any manual changes we make in the future.
Once this is merged, we can tag it as `v4.2.0` and try the release again,
as described in https://github.com/OctoLinker/browser-extension/pull/137#issuecomment-236396330
> Synchronize assets/manifest.json version with package.json

- lib/click-handler.js
- lib/octo-linker.js
- lib/resolver/index.js
- lib/resolver/javascript-universal.js
- lib/resolver/live-resolver-ping.js
- test/click-handler.test.js
While working on adding docker support #62, I've noticed that the handling of external urls is a bit nasty. In my opinion a developer shouldn't care about if a url goes to a cross origin page or not. I moved the `live-resolver-ping` parts into the `click-handler` and wrote a couple test around this.
> Simplify external url handling by remove the ping resolver

- lib/plugins/homebrew-manifest/index.js
- lib/resolver/homebrew-file.js
- lib/resolver/index.js
- test/resolver/homebrew-file.test.js
This makes it so that homebrew formulae in other taps are properly
linked to their dependencies in the default tap. For example:
https://github.com/Homebrew/homebrew-science/blob/1acf4f470fc8c87f6bcbf19b721ebcd09c7fb025/octave.rb#L44
shows a dependency on autoconf, but the relativeFile resolver points to:
https://github.com/Homebrew/homebrew-science/blob/1acf4f470fc8c87f6bcbf19b721ebcd09c7fb025/autoconf.rb
which does not exist. Instead, use a new resolver to fall back to:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/autoconf.rb
> homebrew: use homebrew-core for fallback link

- .travis.yml
During the v4.2.0 release, Travis tried to run the release script on
both Node 4 and Node 6, which resulted in a build [failure]. Besides,
Travis should only try to release from one build environment anyway.
[failure]: https://travis-ci.org/OctoLinker/browser-extension/jobs/148600890#L7346
https://docs.travis-ci.com/user/deployment#Examples-of-Conditional-Releases-using-on%3A
> Publish Chrome extension only when running Node 6

- lib/background.js
- lib/click-handler.js
- test/click-handler.test.js
- test/main-lib.js
This is another fix for #144.
Most of the time a resolver returns either a url or an array of urls. There is only one exception, the `live-resolver-query` resolver. This on returns an object like `{url: '...', method: 'GET' }`. By default all requests are preformed as a http HEAD request. 
Also I refactored the  `background.js` file a bit. Before it was accepting a url-string and a url-object and the were mapped internally. To keep it consistent it accepts only url-object from now on.
> Fix live resolver urls 

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
Now that https://github.com/OctoLinker/browser-extension/pull/134 is
merged, we can just tweak the regex to support linking to formulas in
the homebrew-core tap. See here for details on the syntax:
https://github.com/caskroom/homebrew-cask/blob/714bd04bebd195500843dbb2cdbef21d65ff8852/doc/cask_language_reference/stanzas/depends_on.md#depends_on-formula
Here's a file for testing:
https://github.com/caskroom/homebrew-cask/blob/42437e5fcd93b1a3c95376794e6d5eee2b096160/test/support/Casks/with-depends-on-formula-multiple.rb#L8
> homebrew: support `depends_on formula:` syntax

- lib/plugins/vim/index.js
- lib/resolver/index.js
- lib/resolver/vim-plugin.js
- package.json
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- test/resolver/vim-plugin.test.js
I referred to the Vundle documentation to implement the resolver:
https://github.com/VundleVim/Vundle.vim/blob/11fdc428fe741f4f6974624ad76ab7c2b503b73e/doc/vundle.txt#L196
Here's a file for testing:
https://github.com/gmarik/vimfiles/blob/1f4f26d42f54443f1158e0009746a56b9a28b053/vimrc#L136
Resolves https://github.com/OctoLinker/browser-extension/issues/31
Resolves https://github.com/OctoLinker/browser-extension/issues/41
> Add support for plugins in vimrc files

- .travis.yml
Since we don't usually need to have the extension packages, we can save
build time by packaging them only before a deployment, rather than on
every commit. Here's more info on when the various Travis scripts run:
https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
> Travis: only `npm run package-all` before a deploy

- lib/plugins/javascript/index.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
They're essentially the same, so let's just fold them together to reduce
regex duplication.
> Combine REQUIRE_RESOLVE regex into REQUIRE

- lib/resolver/index.js
This makes it so only one line is needed per resolver.
Maybe we could also do some webpack trickery to make this work like the
plugin auto-loading in ea30b42684cf60d65118562c7ffdcc267067517e, but I
haven't tried to figure that out yet.
> Use `export { default as` syntax to dedupe resolver exports

- lib/pattern-preset.js
- lib/plugins/rust/index.js
- lib/resolver/index.js
- lib/resolver/rust-crate.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- test/resolver/rust-crate.js
This live-resolver PR must be merged first: https://github.com/OctoLinker/live-resolver/pull/18
Resolves https://github.com/OctoLinker/browser-extension/issues/45
Test page: https://github.com/rust-lang/cargo/blob/07c1d9900de40c59b898d08d64273447560ffbe3/tests/config.rs#L1-L5
> Add Rust plugin with 'extern crate'/'use' support

- npm-shrinkwrap.json
The extension reviewers from Firefox and Opera, have noticed that the review build is a lot different than the travis build. Potentially they are getting other dependencies version than us / travis. I'm hoping to fix that problem by adding a shrinkwrap file.
> Add shrinkwrap file

- lib/pattern-preset.js
- lib/plugins/python/index.js
- lib/resolver/index.js
- lib/resolver/python-universal.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- test/resolver/python-universal.test.js
This PR adds basic support for Python and allows clicks on `import` and `from` statements. 
Demo: https://github.com/pallets/flask/blob/master/flask/cli.py
Resolves #33
> Add Python support

- assets/manifest.json
- packages/blob-reader/fixtures/github.com/gist/113827963013e98c6196db51cd889c39.html
- packages/blob-reader/helper.js
- packages/blob-reader/test.js
Resolves https://github.com/OctoLinker/browser-extension/issues/156
It turns out that the only thing preventing this from working (other
than permissions) is determining the path associated with the Blob.
Before, the path was undefined, so the Blob was not initialized
properly. With this change, the path will be set to the filename entered
into the gist.
Assuming that that the filename is set to something reasonable, either
the filename-based language detection or the github-based language
detection will work correctly (at least, for non-relative links).
Here's a test page:
https://gist.github.com/josephfrazier/113827963013e98c6196db51cd889c39
---
Note that we may want to change the manifest.json `permissions` handling
at https://github.com/OctoLinker/browser-extension/blob/ec499e065424b52 …
> Add gist support

- npm-shrinkwrap.json
Following up on #157, this PR adds only our devDependencies to the shrinkwrap file. 
@josephfrazier the package urls are mixed again with. I don't know why. I performed a `npm cache clean` before, but still the same.
> Update shrinkwrap to handle devDep

- lib/click-handler.js
- lib/resolver/homebrew-file.js
- lib/resolver/javascript-file.js
- lib/resolver/relative-file.js
- lib/resolver/ruby-file.js
- test/click-handler.test.js
- test/resolver/homebrew-file.test.js
- test/resolver/python-universal.test.js
- test/resolver/relative-file.test.js
This PR replace the hardcoded base url with a placeholder in different places in order to store the base url in a single location. The placeholder will be replaced by the actual base url before a request made.
> Store base url in a single location

- package.json
`npm run chrome-build` will error on Windows because the `chrome-manifest` script has single quotes which is not escaped properly on Windows.
> Escape quotes so that runs on windows

- .travis.yml
Fixes https://github.com/OctoLinker/browser-extension/issues/194
Note that there's [an npm fix in progress](https://github.com/npm/npm/pull/14117). I've subscribed to it as well as the bug report, so I should be able to revert this once npm has been fixed.
> Travis: use npm@3.10.7

- test/insert-link.test.js
I noticed these while working on https://github.com/OctoLinker/browser-extension/pull/192
EDIT: blocked by https://github.com/OctoLinker/browser-extension/issues/194
> Fix some typos in insert-link.test.js

- appveyor.yml
- karma.conf.js
This uses [Chocolatey] to install `phantomjs` and instructs `karma` to
use that version instead. `phantomjs-prebuilt` still has to be
monkey-patched to workaround the following error:
Error during loading "C:\projects\browser-extension\node_modules/karma-phantomjs-launcher" plugin:
Path must be a string. Received null
[Chocolatey]: https://www.appveyor.com/blog/2014/11/06/appveyor-with-a-hint-of-chocolatey/
> Run tests on AppVeyor

- README.md
- lib/plugins/npm-manifest/index.js
Example: https://github.com/moment/moment/blob/958846899bb4b15405c7ccf2f8cbff1712916b3a/package.json#L27
Spec: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
> Link `typings` and `types` fields in package.json

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
As we had discussed elsewhere, this is a step towards simplifying
insert-link.js to not worry about quotes.
> helper-grammar-regex-collection: don't capture quotes

- lib/resolver/python-universal.js
- test/resolver/python-universal.test.js
Some of the standard library names have been shadowed by user packages
on PyPI. For example, clicking on `argparse` in this [file] should lead
to https://docs.python.org/3/library/argparse.html, not
https://github.com/ThomasWaldmann/argparse/
This commit accomplishes that.
[file]: https://github.com/idank/bashlex/blob/b47fc8a2240af7767ebd33dca39d62a3cf05e0aa/examples/commandsubstitution-remover.py#L3
> python: Try API docs before PyPI

- .travis.yml
- npm-shrinkwrap.json
(This is a follow-up to https://github.com/OctoLinker/browser-extension/pull/195)
npm@4.0.2 is currently the 'latest' tag, and it has the [fix] for
https://github.com/npm/npm/issues/14042
Note that we can't remove the `before_install` section quite yet,
because no Node.js release currently includes npm@4. On the other hand,
having Travis always use the latest npm might be a nice way to learn
about upcoming breakage...
I also had to regenerate npm-shrinkwrap.json, but it's
backwards-compatible, as shown here:
https://travis-ci.org/josephfrazier/browser-extension/builds/176915380
[fix]: https://github.com/npm/npm/pull/14117
> travis: use npm@latest, not 3.10.7

- lib/click-handler.js
- lib/options/options.js
Add option so user can specify if links should be open in a new tab by default. This is disabled by default.
> Add new window option

- assets/style.css
- lib/click-handler.js
- lib/insert-link.js
- lib/options/options.js
- test/click-handler.test.js
- test/insert-link.test.js
This PR tries to solve #209 by making the octolinker links more visible to the user. I added two versions. 
The first one adds a dot next to the line number. After a short fadeIn animation the dot will stay visible. The other is a bit more pushy. A short background color flash makes the link visible to the user. The user can enable/disable both option separately. 
I'm not sure about the default behaviour. Should we enable both options and point the user to the options page?
> Make links more visible to the user

- lib/notification.js
This fix the issue where the update notification was shown twice to the user when browsing on github.com and gist.github.com.  That happened because we stored the version in the LocalStorage. The LS is bounded to the domain and therefore the notification was appearing twice to the user. By using the browser build in storage this can be avoided.
> Store extension version in browser storage

- lib/insert-link.js
- test/insert-link.test.js
While adding support for issue code blocks I noticed the link creation fails if the data attribute values is null or undefined. In order to not break the app I do an early return.
> Do not break when passing null or undefined as data-attr

- lib/pattern-preset.js
- lib/plugins/javascript/index.js
- test/pattern-preset.test.js
Looks like CoffeeScript is broken since we added Presets. This PR will fix the issue by merging the JavaScript and CoffeeScript preset at runtime.
Alternative we could add a CoffeeScript plugin which extends JavaScript  and overwrite the preset function. What would you prefer @josephfrazier?
> Fix CoffeeScript support by merging presets

- assets/style.css
- lib/pattern-preset.js
- packages/blob-reader/blob.js
- packages/blob-reader/fixtures/github.com/issue/code.html
- packages/blob-reader/helper.js
- packages/blob-reader/scripts/update-fixtures.sh
- packages/blob-reader/test.js
- test/pattern-preset.test.js
Finally I managed to resolve links within discussion and other documents like markdown files. By the nature of those files it will not work for relative paths. Also it doesn't work for JSON blocks. Anyway, it's quite handy and provides more value to the user.
> Resolve links in code blocks

- assets/manifest.json
- lib/background.js
- lib/click-handler.js
- lib/options/options.js
- lib/options/storage.js
- test/click-handler.test.js
Collect some basic information to get some insights about how the extension is used. 
**We do not** collect any personal identification information about Users whenever they interact with the OctoLinker.
**We do** collect non-personal identification information about Users whenever they interact with the OctoLinker. Non-personal identification information include the OctoLinker preferences from the option page, the link resolver name which is used to redirect you and if the redirect was succesful or not.
Please note that we use the Analytics extension `ga('set', 'anonymizeIp', true);` to ensure that IP addresses are collected anonymously.
<details><summary>Tracking example</summary>
{
"category": "resolver",
"action": "invoke",
"label": "javascriptUniversal"
}
{
"category": "fetch", …
> Track usage of extension via GA

- lib/background.js
- lib/click-handler.js
Fix for #225. 
@josephfrazier I tried to write some tests for this, but unfortunately the current implementation makes it quite difficult. Basicly we have to fake/reimplement the the message system that we use to communicate with the background script. I'll work on that in a separate PR.
> Fix bug where Firefoxs Pop-up blocker prevents open link in new tab

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
This is done by using the [multiline flag] instead of matching a newline,
then by moving the `^\s*` outside the non-capturing group.
Test page:
https://github.com/kewisch/pyamo/blob/38dc77a833492a22d8ff707001577489f49ba9d6/pyamo/utils.py#L81
[multiline flag]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/multiline
> helper-grammar-regex-collection: Ensure PYTHON_IMPORT doesn't match comments

- README.md
They were broken by
https://github.com/alrra/browser-logos/commit/a335e3357a524160c33e9b0c33b72f7d57d58c6e#diff-1d435e808f4e1e3adde9ff9ff27acce9
> README.md: update browser logo urls

- package.json
This makes it work like `npm run chrome-open`, which navigates to
https://github.com/OctoLinker/browser-extension/blob/master/package.json
See here for info about the `web-ext` flag:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#--pref
> Open package.json url in `npm run firefox-open`

- .travis.yml
Recently, I've been seeing more frequent Travis errors like this:
AssertionError: ' // Most popular rabbit names' == '// Most popular rabbit names'
at fail (webpack:///~/assert/assert.js?9281:200:0 <- test/main-packages.js:10454)
at equal (webpack:///~/assert/assert.js?9281:224:0 <- test/main-packages.js:10478)
at webpack:///packages/blob-reader/test.js:157:8 <- test/main-packages.js:11568
(see https://github.com/OctoLinker/browser-extension/pull/115#issuecomment-229819535)
After a little research, I found that Travis offers a [travis_retry]
function for retrying flaky commands, so I added it to the .travis.yml
file in hopes that it will resolve this annoyance. If you're curious,
here's the `travis_retry` [implementation].
[travis_retry]: …
> .travis.yml: Make phantomjs less flaky

- packages/blob-reader/test.js
Commit d236ab7 (#251) renamed a couple of tests, but one of them
('toString') started causing warnings like the one seen in [this build].
It looks like the warning is coming from [karma-mocha-reporter], but it's
easy enough to work around by simply adding parentheses to the function
names in the test files.
[this build]: https://travis-ci.org/OctoLinker/browser-extension/builds/193866584#L538
[karma-mocha-reporter]: https://github.com/litixsoft/karma-mocha-reporter/blob/9e2f342eeac311ea9824bfd78540b177bc2d3d46/index.js#L479
> blob-reader: Don't use reserved name in tests

- package.json
package.json: Extract `firefox-launch` script
This allows developers to open the extension in Firefox without
rebuilding the extension, which is useful if they have `npm run
firefox-watch` running in another shell.
The `firefox-open` script has `--` on the end so that arguments can
still be passed through it to `web-ext`, as in:
npm run firefox-open -- --firefox=firefoxdeveloperedition
(see https://github.com/OctoLinker/browser-extension/issues/248#issuecomment-273624297)
> package.json: Extract firefox-launch script

- .appveyor.yml
This adds an `appveyor-retry` wrapper around parts of the AppVeyor build
that have intermittently failed in the past. Here are some example
failures:
* https://ci.appveyor.com/project/josephfrazier/browser-extension/build/1.0.44
* https://ci.appveyor.com/project/stefanbuck/browser-extension/build/1.0.177
See the commit messages for more details.
> .appveyor.yml: Retry Chocolatey installs and PhantomJS

- .npmrc
This makes it so developers won't have to type `--save-exact` when
running `npm install`, to keep package.json versions pinned. See d1c6b70
for context.
Note that `--no-optional` is still needed to avoid having `fsevents`
sneak back into npm-shrinkwrap.json. There doesn't seem to be a .npmrc
config for that.
> Add .npmrc with save-exact=true

- npm-shrinkwrap.json
- package.json
I often use commits to save work-in-progress, with the intention of
revising them later. Removing the pre-commit hook makes this faster.
Since `npm run lint` is also in the `pretest` script, it will still be
run on `npm test`, which should be done anyway before opening a pull
request.
> Remove pre-commit hook

- lib/options/storage.js
- npm-shrinkwrap.json
- package.json
This avoids the following deprecation warning upon `npm install`:
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
`web-ext` still uses `node-uuid` indirectly (via `sign-addon` -> `request`),
but I'm working on fixing that too. See https://github.com/mozilla/sign-addon/pull/245
> Use `uuid` instead of `node-uuid`

- lib/app.js
- lib/options/storage.js
- npm-shrinkwrap.json
- package.json
(this is built upon https://github.com/OctoLinker/browser-extension/pull/257 to make development easier)
See https://github.com/OctoLinker/browser-extension/issues/248
I decided to use [chrome-promise] instead of [chrome-storage-wrapper] or [chrome-storage-promise], because it is more popular and better maintained.
The commit messages have more detail, but to summarize: this doesn't quite work yet, seemingly due to some strange errors potentially related to the way the `chrome.storage` functions get wrapped into returning Promises (the same thing happens with the `chrome-storage-*` packages, for what it's worth):
<details>
```
16:09:28.308 Unhandled promise rejection TypeError: promise.then is not a function
Stack trace:
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:328:9 …
```
> Fix Unhandled promise rejection in storage.js

- karma.conf.js
- npm-shrinkwrap.json
- package.json
test/main-lib.js imports `babel-polyfill`, so we don't need any other shims
> Remove `karma-phantomjs-shim`

- lib/resolver/go-universal.js
- test/resolver/go-universal.test.js
While testing the go implementation, I've noticed that some imports doesn't work. I thought that go  reference repo like `github.com/foo/bar` only. I didn't know that you can also import packages form your project like `github.com/foo/bar/baz`. This should point to `https://github.com/foo/bar/tree/master/baz` or `https://github.com/foo/bar/blob/master/baz/baz.go`.
> Fix go package imports

- .appveyor.yml
In https://github.com/OctoLinker/browser-extension/pull/268, there was a
commit that added `eslint-plugin-mocha` to package.json, but not to
npm-shrinkwrap.json. The [Travis build] failed, as expected, but the
[AppVeyor build] passed.
I'm guessing this is because it was using an older version of `npm` that
perhaps doesn't enforce the shrinkwrap as rigorously as the latest
version. Even if that's not the case, this change will make the AppVeyor
build more similar to the Travis build, which is always good.
[Travis build]: https://travis-ci.org/OctoLinker/browser-extension/builds/196900691#L453
[AppVeyor build]: https://ci.appveyor.com/project/stefanbuck/browser-extension/build/1.0.206
> .appveyor.yml: Update npm to latest version

- npm-shrinkwrap.json
- package.json
- webpack.config.js
npm-check -uE
rm -rf node_modules/chokidar/node_modules/fsevents
npm shrinkwrap
Here's some info about the webpack.config.js changes:
* https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
* https://webpack.js.org/guides/migrating/#json-loader-is-not-required-anymore
> Update dependencies (including webpack v2)

- lib/resolver/javascript-file.js
- test/resolver/javascript-universal.test.js
fixes https://github.com/OctoLinker/browser-extension/issues/271
This allows paths like `./modules/es6.symbol` to correctly resolve to
`./modules/es6.symbol.js`
For example: https://github.com/zloirock/core-js/blob/0bb657cfc7834d03fd68c48a1cba70f2ccab20c0/shim.js#L1
EDIT:
Removing the `fileExt` code didn't break any tests, but I'm not sure if it breaks any functionality in practice. @stefanbuck, do you know why it was there?
> javascript-file: Don't strip extension from file names

- package.json
- webpack.config.js
This makes it possible for other tools to use the Babel settings. For
example, `babel-node` can be used during development as a REPL with
files in the repo:
$ babel-node -p "require('./packages/helper-grammar-regex-collection/regex.js')"
{ default: [Function] }
> Move Babel settings from webpack.config.js to package.json

- lib/click-handler.js
- test/click-handler.test.js
The resolver result url of a git-url or github shorthand was causing a ping call to our live-resolver server. By nature, this service can not reach private repo which ends in 404 response. It was working in a previous version, but #174 broke this behaviour.
> Fix private repo handling

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
This partially addresses
https://github.com/OctoLinker/browser-extension/issues/284 by preventing
text like "because it" from being linked as if "use it" referred to a
Rust crate.
> helper-grammar-regex-collection: prevent RUST_CRATE from matching partial

- .appveyor.yml
```
Downloading googlechrome 64 bit
from 'https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi'
Progress: 100% - Completed download of C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\GoogleChrome\56.0.2924.87\googlechromestandaloneenterprise64.msi (48.26 MB).
Download of googlechromestandaloneenterprise64.msi (48.26 MB) completed.
Error - hashes do not match. Actual value was '1450DE87F0289CE725DF1C138BBA2666304FB94BF4476B03C06D058C999D4805'.
ERROR: Checksum for 'C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\GoogleChrome\56.0.2924.87\googlechromestandaloneenterprise64.msi' did not meet 'c47ff551ff8b251268905cd87fb299959e6bcb3640a3e60085a3a7dbf176845f' for checksum type 'sha256'. Consider passing --ignore-checksums if necessary.
The install of …
```
> Ignre checksums when installing chrome from choco

- CONTRIBUTING.md
I left `npm version patch` as-is because `yarn version patch` doesn't do
the same thing (it's interactive instead).
> CONTRIBUTING.md: Use `yarn` instead of `npm run`

- lib/background/newTab.js
- lib/click-handler.js
- lib/options/options.js
This lets the user specify the `active` argument to
[chrome.tabs.create]. If they uncheck the option, new tabs will open in
the background, rather than becoming focused. However, it defaults to
checked, which preserves the current behavior of focusing new tabs.
[chrome.tabs.create]: https://developer.chrome.com/extensions/tabs#method-create
> Add option to open tabs in background

- lib/pattern-preset.js
- lib/plugins/html.js
- packages/blob-reader/fixtures/github.com/issue/code.html
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
Adding HTML import was an easy thing to do. The tricky part is to agree on which file extension we would like to support.
@tunnckoCore was providing the following
- highlight-text-html-basic // => .html, .html
- highlight-text-html-twig
- highlight-text-html-slim
- highlight-text-html-vue
- highlight-text-html-js // => ejs, and probably others
- highlight-text-html-handlebars // => hbs, handlebars, htmlbars
- highlight-text-html-erb
- highlight-text-jade // => jade, pug
what else do we need to add?
[Demo page](https://github.com/Polymer/polymer-analyzer/blob/b438736929167351a212d11a023c1c8849cdcad9/src/test/static/diamond/a.html)
> Add HTML import support

- lib/gh-interface.js
- lib/notification.js
I thought it would be helpful to display the release highlight in the notification, so I created this PR.
The first release notes line defines the highlight and will be displayed in the notification.
> Fetch and display release highlight

- README.md
- lib/pattern-preset.js
- lib/plugins/sass.js
- package.json
- packages/blob-reader/fixtures/github.com/issue/code.html
- test/plugins/sass.test.js
This PR adds support for relative sass imports. It doesn't take [includePaths](https://github.com/sass/node-sass#includepaths) into account. 
[Demo](https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap-grid.scss)
**TODO**
> Add partial support for sass

- README.md
- lib/pattern-preset.js
- lib/plugins/less.js
- test/plugins/less.test.js
This PR adds support for relative less imports. It doesn't take [includePaths](http://lesscss.org/usage/) into account. 
[Demo](https://github.com/less/less-docs/blob/master/styles/index.less)
> Add partial support for less

- packages/helper-grammar-regex-collection/index.js
This way, we don't have to have that big export statement at the
bottom of the file, with all of the variable names repeated.
> helper-grammar-regex-collection: dedupe exports

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
`require ('foo')` is valid JavaScript, so let's support it.
> Allow spaces before parentheses in require()/etc

- lib/plugins/less.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
This follows up on commit 8736eac (#322)
See http://lesscss.org/features/#import-options
Demo page: https://github.com/less/less-docs/blob/315c5b3633d2ff2b94054574cfdf57132aa95eed/styles/index.less#L13
> Less: support `@import` keywords

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
This follows up on issue #326. `require_relative` links are clickable with this PR but do not always work. For example, the first link on <a href="https://github.com/MatthewDG/ormellow/blob/master/lib/sql_object.rb">this page</a> tries to resolve a path to a page dedicated to a Ruby gem, but the other two require_relative links work fine. On many other pages such as <a href="https://github.com/rails/rails/blob/master/actioncable/test/subscription_adapter/redis_test.rb">this one</a>, the links just throw a 404 error in the console.
> Ruby require_relative support

- lib/click-handler.js
- lib/plugins/haskell.js
- lib/plugins/less.js
- lib/plugins/sass.js
- lib/resolver/github-search.js
- lib/utils/fetch.js
- test/plugins/haskell.test.js
- test/plugins/less.test.js
- test/plugins/sass.test.js
- test/resolver/github-search.test.js
Today, I tried to implement support for [less includePaths](http://lesscss.org/usage/) and [sass includePaths](https://github.com/sass/node-sass#includepaths). As expect this is really tricky to implement and maybe even impossible. There is no single point of truth where this property is defined. It could be everywhere. Of course we could search  in common places like in `gruntfile.js` or `gulpfile.js` file, but even that isn't entirely accurate. If the path isn't stored a string we're screwed.
Luckily, an idea came to my head and thought giving it a try. Why not using GitHub`s [search API](https://developer.github.com/v3/search/). I know that this isn't very accurate either, but at least it works in many (hopefully in almost every) case. 
I need a bit more time to think about it. I …
> Fallback to fuzzy search

- README.md
- lib/plugins/npm-manifest.js
Test page: https://github.com/northbrookjs/northbrook/blob/84a31d4f54db97b7448216b9bb04fc4671e28092/src/plugins/exec/__test__/a/package.json#L5-L6
Fixes https://github.com/OctoLinker/browser-extension/issues/235
> package.json plugin: link `module` and `jsnext:main` fields

- webpack.config.js
This will avoid the following error once webpack is updated:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.output.path: The provided value "dist" is not an absolute path!
See https://github.com/josephfrazier/octopermalinker/commit/6e0e4fedc9613026b196d99bcb0a371f0eb0b287
> webpack: Use absolute output path

- lib/pattern-preset.js
- lib/plugin-manager.js
- lib/plugins/bower-manifest.js
- lib/plugins/composer-manifest.js
- lib/plugins/dot-net-core.js
- lib/plugins/gemfile-manifest.js
- lib/plugins/npm-manifest.js
- packages/helper-grammar-regex-collection/test.js
- test/pattern-preset.test.js
Following up on https://github.com/OctoLinker/browser-extension/pull/332#issuecomment-289582089,
this change allows filenames like [dev-requirements.txt] to be linked.
Making this possible required some changes to the file path matching
mechanism, which can be found in commit 468d46a. After that, it was
straightforward to match the additional *requirements.txt patterns (commit 3e94b62),
then add a test for the linking regex (commit a595a85).
Since this pull request has both the filepath refactoring and an
additional feature, I think it should be merged using GitHub's "Rebase and merge"
option, to preserve the meaning of the individual commits.
[dev-requirements.txt]: https://github.com/alanhamlett/pip-update-requirements/blob/c8d64c8c865be48f1654052a546f68f37e718ff9/dev-requirements.txt
> Support *requirements.txt files

- packages/helper-grammar-regex-collection/test.js
This allows the `go` tests to be handled alongside the others, rather
than duplicating the test logic. The diff is best viewed ignoring
whitespace changes: https://github.com/OctoLinker/browser-extension/pull/340/files?w=true
> test: Dedupe grammar tests

- lib/utils/builtins-docs.js
This module is internal, but is nevertheless used in some places.
Here's one example:
https://github.com/isaacs/node-touch/blob/f73938c01bd10fe70fae5af3f37fc8c6162e9852/touch.js#L2
> javascript: Fix link to Node's `constants` module

- lib/octo-linker.js
- lib/plugins/css.js
- lib/plugins/docker.js
- lib/plugins/gemfile-manifest.js
- lib/plugins/go.js
- lib/plugins/haskell.js
- lib/plugins/homebrew-manifest.js
- lib/plugins/html.js
- lib/plugins/javascript.js
- lib/plugins/less.js
- lib/plugins/python.js
- lib/plugins/requirements-txt.js
- lib/plugins/ruby.js
- lib/plugins/rust.js
- lib/plugins/sass.js
- lib/plugins/typescript.js
- lib/plugins/vim.js
- test/plugins/docker.test.js
Since so many of the plugins have the same `parseBlob` implementation
(just with a different set of regexes), let's make it so that the
plugins can just specify the regexes to use with `insertLink`
> Extract common parseBlob() from plugins

- lib/octo-linker.js
- lib/plugin-manager.js
- lib/plugins/bower-manifest.js
- lib/plugins/composer-manifest.js
- lib/plugins/css.js
- lib/plugins/docker.js
- lib/plugins/dot-net-core.js
- lib/plugins/gemfile-manifest.js
- lib/plugins/go.js
- lib/plugins/haskell.js
- lib/plugins/homebrew-manifest.js
- lib/plugins/html.js
- lib/plugins/javascript.js
- lib/plugins/less.js
- lib/plugins/npm-manifest.js
- lib/plugins/python.js
- lib/plugins/requirements-txt.js
- lib/plugins/ruby.js
- lib/plugins/rust.js
- lib/plugins/sass.js
- lib/plugins/typescript.js
- lib/plugins/vim.js
- test/load-plugins.test.js
As mentioned in https://github.com/OctoLinker/browser-extension/pull/341#issuecomment-293080486,
this lets us avoid unnecessarily instantiating the class, and just use
the plugin directly instead.
> Make plugins regular objects instead of classes

- lib/plugins/homebrew-manifest.js
- test/plugins/homebrew-manifest.test.js
Test page: https://github.com//Homebrew/homebrew-science/blob/1acf4f470fc8c87f6bcbf19b721ebcd09c7fb025/octave.rb#L44
> homebrew: Add `.rb` extension to target

- lib/plugins/vim.js
- test/plugins/vim.test.js
Commit 9750462 accidentally broke vimrc support, but this fixes it.
Test page: https://github.com/gmarik/vimfiles/blob/1f4f26d42f54443f1158e0009746a56b9a28b053/vimrc#L140-L144
> vim: Use `target` argument instead of `shorthand`

- package.json
- packages/helper-grammar-regex-collection/regex.js
- yarn.lock
https://github.com/slevithan/xregexp/issues/162 has been fixed in
`xregexp` v3.2.0, so we don't have to work around it anymore.
> Upgrade `xregexp` to v3.2.0, remove 'x' flag workaround

- package.json
This addresses https://github.com/OctoLinker/browser-extension/issues/351
by removing a couple of `Function()` calls from `dist/app.js`. Here's
the diff in the output of `grep ' Function(' dist/app.js`:
```diff
diff --git a/before.txt b/after.txt
index cfc9de2..c5c2ee1 100644
--- a/before.txt
+++ b/after.txt
@@ -1,4 +1,2 @@
-  ? window : typeof self != 'undefined' && self.Math == Math ? self : Function('return this')();
g = g || Function("return this")() || (1,eval)("this");
-      invoke(typeof fn == 'function' ? fn : Function(fn), args);
? window : typeof self != 'undefined' && self.Math == Math ? self : Function('return this')();
```
Hopefully, the remaining two calls will be ok, since they simply get the
global object, rather than have the potential to execute arbitrary code.
EDIT: …
> Inline babel helpers rather than requiring them

- CONTRIBUTING.md
The most recent release was `minor` when it probably should have been
`patch`, so make a note about this for later.
> CONTRIBUTING.md: Add update notification info to Release Checklist

- README.md
As [`browser-extension/packages/helper-grammar-regex-collection/index.js` line 15](https://github.com/OctoLinker/browser-extension/blob/7a12c2665ba5d5999d6cb4786449eef996d33b91/packages/helper-grammar-regex-collection/index.js#L15) shows, `require_relative` is supported – it just isn't mentioned in the README. Before looking that up I assumed from the README that this extension didn't support that keyword.
> Note support for Ruby `require_relative` in README

- lib/plugins/dot-net-core.js
- lib/plugins/helper/process-json.js
The extension doesn't parse framework-specific dependencies in project.json file.
Here is an example of such file:
https://github.com/olsh/todoist-net/blob/master/src/Todoist.Net.Tests/project.json (lines 13 and 21)
> Fix .net core parsing for framework-specific dependencies

- lib/plugins/javascript.js
- packages/helper-grammar-regex-collection/test.js
This makes it possible to link package names that are escaped, due to being
in JSdoc-style comments, for example:
https://github.com/angular/core-builds/blob/85cbe3f8d6107af033b0f8b56456c181cbcb5eb7/%40angular/core.js#L3260
From https://docs.npmjs.com/files/package.json#name:
> The name ends up being part of a URL, an argument on the command line,
> and a folder name. Therefore, the name can't contain any non-URL-safe
> characters.
From https://devdocs.io/javascript/global_objects/encodeuricomponent:
> `encodeURIComponent` escapes all characters except the following:
> alphabetic, decimal digits, `- _ . ! ~ * ' ( )`
Additionally, '@' and '/' are allowed, since they are part of scoped
package names.
This addresses https://github.com/OctoLinker/browser-extension/issues/338
> Remove non-URL-safe characters from npm package names

- lib/octo-linker.js
- package.json
- yarn.lock
This PR updates `github-injection` to make use of the latest improvements see https://github.com/OctoLinker/injection/releases
> Update github-injection to latest version

- lib/plugins/npm-manifest.js
- lib/resolver/github-shorthand.js
Demo: https://github.com/josephfrazier/prettier_d/blob/3319ee19d8d9bcd12a10e3b84dfbc96b702af6e5/package.json#L44
Before: `prettier` link goes to https://github.com/josephfrazier/prettier#cosmiconfig-master-branch
After: `prettier` link goes to https://github.com/josephfrazier/prettier/tree/cosmiconfig-master-branch
Fixes https://github.com/OctoLinker/browser-extension/issues/374
See https://github.com/robertkowalski/github-url-from-username-repo/commit/534faff3e1645e61eb80da84885226800c6bf2ff
> Support commit-ish in package.json

- lib/plugins/html.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
Closes #382 
Basic handling of `<script src="myfile.js"></script>`. See the new tests for a full breakdown of what I've handled.
While I was doing this, I noticed that absolute URL sources, such as on a CDN or similar, do not work with this. I can't see it being super useful, but what are your thoughts on putting something like:
```js
if (/^(https?:)?\/\//.test(target)) {
return [target];
}
```
in the `resolve` function so that the absolute URLs open up where they target.
> Handle HTML script tags

- lib/click-handler.js
- lib/gh-interface.js
- fixes tooltip remaining as `Redirecting  🚀` even after opening link in new tab
- adds `removeTooltip` function in `gh-interface.js` 
---------
Thank you for making this amazing extension. :clinking_glasses:
> fixes tooltip remaining as `redirecting` after opening link in new tab

- lib/plugins/java.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- test/plugins/java.test.js
Adding full support for Java isn't an easy task. After many nights working on this over the last couple of months, I decided to start with a simple version as a MVF minimum viable feature 😉 
As a first step, OctoLinker links java SE and EE imports to their documentation page. It doesn't take the version set in the pom.xml into account. Instead, OctoLinker tries to find the class either in SE/EE version 9, 8 and last but not least 7. 
https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/ui/Model.java#L19
> Add a little Java support

- assets/manifest.json
- lib/app.js
- package.json
- test/main-lib.js
It's been supported for a while now, I'd argue that most babel transforms you have there are unnecessary. I think you probably exclusively need the JSX transform.
> Drop core-js

- lib/plugin-manager.js
- lib/plugins/bower-manifest.js
- lib/plugins/composer-manifest.js
- lib/plugins/css.js
- lib/plugins/docker.js
- lib/plugins/dot-net-core.js
- lib/plugins/dot-net.js
- lib/plugins/gemfile-manifest.js
- lib/plugins/go.js
- lib/plugins/haskell.js
- lib/plugins/html.js
- lib/plugins/java.js
- lib/plugins/javascript.js
- lib/plugins/less.js
- lib/plugins/nodejs-relative-path.js
- lib/plugins/npm-manifest.js
- lib/plugins/python.js
- lib/plugins/requirements-txt.js
- lib/plugins/ruby.js
- lib/plugins/rust.js
- lib/plugins/sass.js
- lib/plugins/typescript.js
- lib/plugins/vim.js
Today I noticed that some `pathPatterns` were wrong after converting the string into a RegExp. This was leading into loading the wrong plugin. Especially the escaping wasn't correct. For example `.css$` was converted to `/.css$/` where it should be `/\.css$/`. This PR is converting all `pathPatterns` string into a RegExp to ensure proper escaping.
> Convert pathPatterns to RegExp to ensure proper escaping

- lib/app.css
This resolves #391 by using a more specific css selector.
> Update css selector to fix incorrect position of the permalink link

- assets/manifest.json
- package.json
Support for Java added and various bug fixes! 🚀
Do you know what's the second-most popular language on GitHub after JavaScript ... correct Java. Today we're happy to announce that OctoLinker is finally supporting a little Java. As a first step, OctoLinker links java SE and EE imports to their documentation page. It doesn't take the version set in the pom.xml into account. Instead, OctoLinker tries to find the class either in SE/EE version 9, 8 and last but not least 7.
- Update css selector to fix incorrect position of the permalink link #396
- Fix a few broken plugins #392 
[v4.13.0...v4.14.0](https://github.com/OctoLinker/browser-extension/compare/v4.13.0...v4.14.0)
Huge thanks to our contributor: @bfred-it
> Release 4.14.0

- .gitattributes
See https://help.github.com/articles/dealing-with-line-endings/
Addresses https://github.com/OctoLinker/browser-extension/pull/398#issuecomment-344091708
> .gitattributes: Force .js files to have LF line endings

- .travis.yml
- yarn.lock
The following commits removed dependencies from package.json, but didn't
update yarn.lock:
* 5c8c1b19659c65f63782644efb95e6ea005a7aa3: Drop core-js (#393)
* d9038106635ee28ad2cef106387c7515646be532: Drop most babel transforms (#394)
This change updates yarn.lock, and also adds a bit to .travis.yml that
fails the build if yarn.lock changed after running `yarn`.
> Update yarn.lock and have Travis enforce it

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
Anywhere that a string literal can be used to import files in JS, backticks are valid:
```js
const someThing = require(`aw-yeah.js`)
```
This does not include ES Module imports/exports - those are restricted to single/double quotes.
I looked around for some tests to modify so I could add extra test cases, but I didn't see any tests that covered this - the tests in `test/grammar/` aren't being executed, and it looks like they were written for an older version of the library anyway.
> Support require calls using backtick-quoted strings in JS

- lib/gh-interface.js
Yesterday I noticed that the loading message (tooltip) doesn't work anymore. After looking at the documenation page of primer css (GitHub's ui component framework) it seems like they introduced a delay before showing a tooltip. This PR removes the delay to get instant feedback about the loading state
> Fix loading message by removing tooltip delay

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
Today I noticed that a few plugins doesn't work for deleted and added lines in the PR diff view. A deletion starts with a minus sign and an addition with a plus sign. Some RegExp exclude those lines by using the `^` followed by the keyword expression. This PR tweak them to take the diff signs into account. 
@josephfrazier I only updated the RegExp which already started with the `^` anchor. Maybe we should update the other as well. What do you think?
> Take addition and deletion sign into account when building regex

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
#409 introduced a bug that stopped OctoLinker from inserting links. On GitHub a diff line starts with a whitespace character if the line is not modified which the RegeEx doesn't take into account.
> Handle leading whitespace in diff line

- package.json
This should fix https://github.com/OctoLinker/browser-extension/issues/418
See https://stackoverflow.com/questions/20765337/how-to-fix-is-not-an-internal-or-external-command-error/20765382#20765382
> package.json: Remove `./` from chrome-launch path

- package.json
* Use `yarn` instead of `npm run`
* Explicitly run `node` for `chrome-launch`
This (hopefully) fixes https://github.com/OctoLinker/browser-extension/issues/418
> package.json: Improve Windows compatibility of scripts

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
This expands the existing .net proj file linking to also support [cli references](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility) via `DotNetCliToolReference`.
The tests are passing locally, but as per #418 I'm unable to build & test it myself 😞 
An example of where this would work is https://github.com/aspnet/DotNetTools/blob/3c20e7c45beb5d45547b549964a3da83b2e8303e/samples/dotnet-watch/LaunchAnyCommand/LaunchAnyCommand.csproj#L6-L10
> Add cli tool support to .net proj files

- lib/plugins/dot-net.js
This adds support for F# project files which are the same xml format as those of C# & VB.Net. It also adds support for [props files](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build) which are used to extend them. MSBuild assumes a file name of `Directory.Build.props` but you can also manually import files of any name which commonly use the `.props` extension.
Sample F# project file
https://github.com/cartermp/GiraffeSample/blob/bbb8a0d3d08a31bf8d9ecac75457cd41953e8414/LunchAPI/LunchApi.fsproj
Example `.props` file without references
https://github.com/aspnet/Mvc/blob/747420e5aa7cc2c7834cfb9731510286ded6fc03/Directory.Build.props
Example `.props` file with references
https://github.com/aspnet/Mvc/blob/747420e5aa7cc2c7834cfb9731510286ded6fc03/src/Directory.Build.pr …
> Add support for F# project files and .net props files

- packages/core/octo-linker.js
- packages/core/plugins/bower-manifest.js
- packages/core/plugins/composer-manifest.js
- packages/core/plugins/dot-net-core.js
- packages/core/plugins/helper/process-json.js
- packages/core/plugins/npm-manifest.js
- packages/helper-insert-link/__tests__/__snapshots__/index.js.snap
- packages/helper-insert-link/__tests__/index.js
- packages/helper-insert-link/index.js
**This PR based on #435! Related changes starting from 790dc43.**
In preparation for #277, this PR refactors the `helper-insert-link` package to return an array of matches. This allows us to separate the matching and link creation process. A match is an object with the following two properties. 
- `link` is a DOM reference to the a-tag element. 
- `data` represents the data-attributes.
Note, I moved the data attribute assignment to the `core` package to retain the functionality until we complete work for #277. 
To review related changes for this PR, you can use this [link](
https://github.com/OctoLinker/OctoLinker/compare/c36144c6b60351a21e8fd173ff1d81b796ff77b8...0da292982b5f76e940666d94e136085788e7e96c?w=1) or start reviewing from 790dc43
> Refactor helper-insert-link package

- packages/core/octo-linker.js
Fix for #443. This was caused by combination, where the [composer plugin](https://github.com/OctoLinker/OctoLinker/blob/b175d59f1bd6f630ffb655dac6449a674852aa7f/packages/plugin-composer-manifest/index.js#L8) returns `undefined` if the json key is `php` and a not solid `forEach` loop in the octolinker core.
> Handle undefined results in the match array

- packages/core/utils/fetch.js
Yesterday, a new version of OctoLinker was released with the option to opt-out of logging. Today, I noticed that this isn't working as expected. Setting `DNT: 1` cause the browser to throw the following error.
```
Refused to set unsafe header DNT
```
I'm not 100% sure why I can't set this header, but I worked around by introducing a custom header called `do-not-track`.
> Use custom header to avoid clash with the DNT standard

- packages/core/octo-linker.js
- packages/plugin-bower-manifest/index.js
- packages/plugin-composer-manifest/index.js
- packages/plugin-dot-net-core/index.js
Hi,
I noticed that OctoLinker is throwing an error when viewing composer.json and doesn't work in general with it. Short inspection showed that some of the changes made in March were not reflected in plugins using @octolinker/helper-process-json which lead to finding few more issues, but in the end and got it to work.
Let me know if anything needs improving.
> Fix bower, composer, and dotnet plugins

- packages/plugin-haskell/__tests__/index.js
- packages/plugin-haskell/index.js
- packages/plugin-haskell/package.json
- packages/resolver-hoogle-search/__tests__/index.js
- packages/resolver-hoogle-search/index.js
- packages/resolver-hoogle-search/package.json
In my use case we keep several Haskell projects in one repository (monorepo approach). This PR extends search to modules relative to Haskell project root (not git root). It is detected by cutting current path on `src`, `lib`, `app`, or `test`. Also adds navigation in test suites.
> Add support for non repo root Haskell projects.

- packages/resolver-hoogle-search/__tests__/index.js
- packages/resolver-hoogle-search/index.js
Changes I made on @kfigiela PR's introduced a bug. 
> This simplification is not correct. Note that we use `apiUrl` for JSON API lookup. However, in case that more than one package provides module with the same name I redirect to search page that indicates matches (`hoogleSearchUrl` that lacks `&mode=json` parameter). Now it redirects to JSON response.
> Example use case: follow `Net.IPv4` import on https://github.com/rlupton20/vanguard-dataplane/blob/293e2e34c31b17051baa5cf02824c275aa82e772/app/Debug/PacketParsing/IP4.hs
> Now it redirects to https://hoogle.haskell.org/?hoogle=Net.IPv4%20is:module%20is:exact&mode=json which is not very useful, however search page looks better https://hoogle.haskell.org/?hoogle=Net.IPv4%20is:module%20is:exact …
> redirect to hoogle search page when search returns more than one result

- packages/core/octo-linker.js
- packages/core/package.json
- packages/helper-sort-urls/__tests__/index.js
- packages/helper-sort-urls/index.js
- packages/helper-sort-urls/package.json
Yesterday, I noticed that in some cases, I have to wait quite long time for a redirect. For example ur [JavaScript resolvers](https://github.com/OctoLinker/OctoLinker/blob/master/packages/plugin-javascript/index.js#L21-L59) returns an Array of possible urls which is sort by the most common cases. 
```js
[
'{BASE_URL}path/file.js',
'{BASE_URL}path/file/index.js',
'{BASE_URL}path/file.jsx',
'{BASE_URL}path/file/index.jsx',
'{BASE_URL}path/file.ts',
'{BASE_URL}path/file/index.ts',
'{BASE_URL}path/file.tsx',
'{BASE_URL}path/file/index.tsx',
'{BASE_URL}path/file.ls',
'{BASE_URL}path/file/index.ls',
'{BASE_URL}path/file.json',
'{BASE_URL}path/file/index.json',
'{BASE_URL}path/file',
]
```
This makes resolving less popular cases quite slow. In [our …
> Speed up linking 

- packages/core/click-handler.js
- packages/plugin-css/index.js
- packages/plugin-docker/__tests__/index.js
- packages/plugin-docker/index.js
- packages/plugin-dot-net-core/__tests__/index.js
- packages/plugin-dot-net/__tests__/index.js
- packages/plugin-html/index.js
- packages/plugin-java/__tests__/index.js
- packages/plugin-javascript/__tests__/index.js
- packages/plugin-requirements-txt/index.js
- packages/plugin-ruby/index.js
- packages/plugin-rust/__tests__/index.js
- packages/resolver-live-query/index.js
- packages/resolver-nuget/index.js
A resolver can return either a string, an array of strings, an object or a function. This is quite confusing. This PR aims to  simplify this. Apart from the `github-search` resolver all other resolvers are returning either a string or an array of strings.
> Adjust resolver to return a single string or an array of string whenever possible

- packages/helper-grammar-regex-collection/go.js
- packages/helper-grammar-regex-collection/test.js
- packages/plugin-go/__tests__/index.js
- packages/plugin-go/index.js
- packages/plugin-go/package.json
Replacement for #478 to add support for kubernetes imports. 
Test url: https://github.com/kubernetes/ingress-gce/blob/6f8bdc9fad1b5576d4fe07900301a133652a8892/cmd/glbc/main.go#L31
> Add support for k8s.io

- package.json
- webpack.config.js
Yesterday, I noticed that our production build is quite big. Just our `app.js.map` has already 1.5 MB. I think we don't need to ship source maps and therefore I disabled source maps for the production build.
> Do not create source maps for production build

- .eslintignore
- _jestsetup.js
- e2e/automated.test.js
- e2e/diff-fixtures.json
- e2e/generate-fixtures-json.js
- jest.config.js
- package.json
- packages/blob-reader/__snapshots__/test.js.snap
- packages/blob-reader/blob.js
- packages/blob-reader/helper.js
- packages/blob-reader/index.js
- packages/blob-reader/package.json
- packages/blob-reader/test.js
- packages/core/octo-linker.js
- packages/helper-process-json/__tests__/index.js
- packages/helper-process-json/index.js
- packages/helper-regex-builder/__tests__/index.js
- packages/helper-regex-builder/index.js
- packages/plugin-bower-manifest/index.js
- packages/plugin-composer-manifest/index.js
- packages/plugin-dot-net-core/index.js
- packages/plugin-npm-manifest/index.js
- yarn.lock
This turned into a slightly bigger Pull Request than I usually prefer. In order to support `package.json` `bower.json` and `composer.json` files in a Pull Request diff view, I had to make changes all over the place. I'll quickly outline what I did and why this was necessary.
Our plugins for the mentions files above relay on a well formatted json object. This is the case when looking at a single file, but not in a Pull Request view which is in most cases just a subset of the actual file. 
In order to fix #71 I had to ensure that we always have a valid JSON file to operate on. Therefore I added two methods to our [blob-reader](https://github.com/OctoLinker/OctoLinker/tree/master/packages/blob-reader) package. 
This method allows us to fetch the raw underlay blob of the current blob. We only …
> Link npm dependecies in Pull Request

- .gitignore
- e2e/automated.test.js
- e2e/diff-fixtures.json
- package.json
- packages/blob-reader/helper.js
- yarn.lock
That was a journey to get this Pull Request working.
At the beginning I discovered that the selector that I was using to get the parents commit sha from, isn't available on a Pull Request. Then I found out that GitHub returns different HTML markup when user is signed-in or signed-out. Last but not least, I figured out that Travis CI secretes are tied to the repository and that forks don't have access to the encrypted variables. 
For authenticated user we get the parent sha from a hidden input field named `comparison_start_oid`. For anonymous users we extract the sha from a URL I found in the markup (this is mainly needed to get CI working). On the master branch we run E2E tests as an authenticated user to have a real world environment.
> Get parent sha on PR diff view

- packages/plugin-javascript/index.js
This implements https://github.com/OctoLinker/OctoLinker/issues/496, which allows to jump to .js files from .vue.
This link should work:
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/components/Item.vue#L30
I'm not entirely sure regarding tests, can you point me how that should work?
> Support JS import in Vue files

- yarn.lock
We receive a lot timeouts from our E2E tests recently. I already increased the timeout to 20 sec, but they are still failing. Updating puppeteer and all related dependecies like `jest-puppeteer` and `jest` seems to fix this issue
> Update puppeteer related dependecies to lastest version

- e2e/automated.test.js
- packages/core/octo-linker.js
This is a possible implementation for #453, we observe the DOM, if any new `.blob-expanded` nodes are added, then the extension is rerun.
As far as testing goes, I will wait for feedback, I added a single test that clickes the specific `.js-expand` element and then tries to process a single line from it.
> Rerun Octo-Linker when blobs are expanded

- e2e/fixtures/docker/Dockerfile
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- packages/plugin-docker/__tests__/index.js
- packages/plugin-docker/index.js
- packages/plugin-docker/package.json
Hey OctoLinker team, thank you for the great extension and reviewing my PR. Looking forward to your feedback. :)
Adds support for linking to relative Docker entrypoint files to the Docker plugin using the relative file resolver.
Closes issue #431 
The ENTRYPOINT line in [docker-library/wordpress:php5.6/apache/Dockerfile@6a085d9#L59](https://github.com/docker-library/wordpress/blob/6a085d90853b8baffadbd3f0a41d6814a2513c11/php5.6/apache/Dockerfile#L59) should resolve to [docker-library/wordpress:php5.6/apache/docker-entrypoint.sh@6a085d9](https://github.com/docker-library/wordpress/blob/6a085d90853b8baffadbd3f0a41d6814a2513c11/php5.6/apache/docker-entrypoint.sh)
Official repo links (example: `
FROM php:5.6-apache` on line 1 in the same file) should still resolve to hub.docker.com
> Add support for linking to Docker entrypoint files

- e2e/fixtures/docker/Dockerfile
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
Fixes #515 - the Docker image link should not include the whitespace preceding `ubuntu:16.04 AS base` in https://github.com/jrottenberg/ffmpeg/blob/master/docker-images/4.0/ubuntu/Dockerfile#L8
> Do not capture whitespace in Dockerfile image link

- packages/helper-settings/SettingsForm.js
Passing `undefined ` wasn't removing the value from store when users clears token field.
> Remove token from storage when user clears token field

- packages/blob-reader/fixtures/github.com/blob/89f13651df126efdb4f1e3ae40183c9fdccdb4d3.html
- packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_split.html
- packages/blob-reader/fixtures/github.com/commit/b0775a93ea27ee381858ddd9fa2bb953d5b74acb_unified.html
- packages/blob-reader/fixtures/github.com/gist/113827963013e98c6196db51cd889c39.html
- packages/blob-reader/fixtures/github.com/issue/code.html
- packages/blob-reader/fixtures/github.com/pull/comments.html
- packages/blob-reader/fixtures/github.com/pull/diff.html
- packages/blob-reader/helper.js
Today I noticed that Travis is failing since almost 2 weeks. GitHub changed the markup for Pull Requests view and the original implementation wasn't able to handle this. They renamed the button which contains the full blob url from `View` to `View file`. 
I'm really surprised that no one has noticed this before.
> Fix PR linking after markup change

- e2e/fixtures/docker/Dockerfile
Looks like hub.docker.com was updating some webserver config to remove trailing slashes.
> Remove trailing slash to fix E2E

- packages/core/click-handler.js
- packages/core/loader.js
- packages/core/octo-linker.js
- packages/core/package.json
- packages/helper-insert-link/__tests__/index.js
- packages/helper-insert-link/index.js
- packages/helper-normalise-resolver-results/__snapshots__/test.js.snap
- packages/helper-normalise-resolver-results/index.js
- packages/helper-normalise-resolver-results/package.json
- packages/helper-normalise-resolver-results/test.js
- packages/plugin-java/__tests__/index.js
- packages/plugin-javascript/__tests__/index.js
- packages/plugin-rust/__tests__/index.js
- packages/resolver-live-query/index.js
This is one (of a few) changes which are needed to implement #277.
On app startup it prefetch all live resolver urls at once in the background by calling a bulk endpoint. For details check out https://github.com/OctoLinker/live-resolver/pull/59. If a user clicks on a link, the click handler will check an internal cache first. If the requested resource isn't available it will fallback to the old behaviour. 
With this Pull Request I want to verify that our live resolver server is able to handle such traffic increase. The timing for this is perfect. It's one week before Christmas which I assume is already a less busy week than any other week. Also in case something goes really bad, it won't affect that many people.
> Fetch live resolver urls in background 

- packages/blob-reader/test.js
The HTML markup for diffs changed yesterday. As always, before investing further how to fix this let's see if this is a permanent change or just a temporary change.
> Skip failing test for now

- packages/core/loader.js
I did a stupid mistake in the previous implementation. For every URL within a resolve item it was duplicating the resolves items wich caused N+1 requests for every package. Luckily it was just sending two request for each package
> Fix to not duplicate package send to live-resolver

- packages/helper-sort-urls/__tests__/index.js
- packages/helper-sort-urls/index.js
With the recent changes the helper-sort-urls needs to be able to handle results returned by helper-normalise-resolver-results.
> Handle normalise resolver results

- README.md
They closed the stickermule market place see https://twitter.com/stickermule/status/960959199910883329.  The demand to buy stickers was quite low anyway.
> Remove stickermule market link

- e2e/automated.test.js
- packages/plugin-javascript/__tests__/index.js
- packages/plugin-javascript/index.js
Over the past few years, bower lost popularity in favour of npm. Even they recommend using npm or yarn for front-end projects nowadays. OctoLinker still supports `bower.json` files, but remove the first-class support for ES6 modules and CommonJS and resolve to npm only form now on.
> Remove first-class support for bower

- packages/helper-insert-link/__tests__/__snapshots__/index.js.snap
- packages/helper-insert-link/__tests__/index.js
- packages/helper-insert-link/index.js
- packages/plugin-npm-manifest/index.js
Bugfix for #539.
OctoLinker stopped working, because the key `decompress-response` was defined with a boolean value instead of a string. 
```
"browser": {
"decompress-response": false,
"electron": false
},
```
This was causing the following runtime error
`TypeError: Cannot read property 'length' of undefined`. 
https://github.com/OctoLinker/OctoLinker/blob/cbbb95b5757e275cc98f16f355a532fe40aa92d3/packages/helper-insert-link/index.js#L32
I fixed this issue in two places. First, the npm plugin returns early if the given value is not from type string. Second, if a capture group is empty (which should be never the case), the current node will be returned without adding a link.
> Does not bail out when capture group is empty

- packages/ratelimit-notification/__tests__/__snapshots__/messages.js.snap
- packages/ratelimit-notification/__tests__/index.js
- packages/ratelimit-notification/__tests__/messages.js
- packages/ratelimit-notification/__tests__/parse-github-header.js
- packages/ratelimit-notification/index.js
- packages/ratelimit-notification/messages.js
- packages/ratelimit-notification/package.json
- packages/ratelimit-notification/parse-github-header.js
- packages/user-interface/index.js
This PR is in preparation for another PR which will replace the try-load strategy to resolve relate files with an actual GitHub API call. This API endpoint returns a tree of the repositories file structure which we can use to resolve relative links much faster https://developer.github.com/v3/git/trees/. However, this PR is just about adding a rate limit notification component to inform the user about various states see `messages.js`
> Add rate limit notification component

- packages/helper-settings/index.js
OctoLinker is using the Chrome Storage API (not to be confused with localStorage ) to store settings. In some case user data where automatically synced with the Chrome profile. Today, I came across this quote from the documentation:
> Confidential user information should not be stored! The storage area isn't encrypted.
Chrome storage is isolated between extensions, there is no way leak data with another extensions or script running on the same webpage. This PR disables the  sync functionality and stores all data just in the local browser storage.
> Stop using sync API for settings in favor of local storage

- packages/helper-insert-link/style.css
This should fix #639, can you ensure that it doesn't break other parts I might have not considered?
Both should remain unchanged
<blockquote>
```js
require('mem')
```
</blockquote>
https://github.com/OctoLinker/OctoLinker/pull/624/files#diff-6d7f932c7f64e54bb76f6a42949338bbR5
> Limit Markdown-related style to Markdown files only

- e2e/fixtures/markdown/readme.md
Add fixture to cover markdown imports using End2End tests.
> Add fixture for readme

- packages/helper-normalise-resolver-results/__snapshots__/test.js.snap
- packages/helper-normalise-resolver-results/index.js
- packages/helper-normalise-resolver-results/test.js
The `ping` event caused 35M hits over the last 30 days. Most of them contained an invalid url like`https://fmt`. Filtering out those url will avoid unnecessary requests and delays on the live resolver server.
> Remove invalid ping urls before calling resolver api

- packages/core/app.js
- packages/helper-normalise-resolver-results/__snapshots__/test.js.snap
- packages/helper-normalise-resolver-results/index.js
- packages/helper-normalise-resolver-results/test.js
The changes made in #650 caused an issue, which stopped linking relative files in private repos. All files were resolved through the [OctoLinker API](https://github.com/octolinker/api) which obviously doesn't work for private repos.
> Fetch internal files using the GitHub tree API

- packages/helper-settings/SettingsForm.js
The previous behaviour to store a token was quite confusing and not obvious at all. After entering the token you had to press ENTER to actual store it. Most of the times a token is insert from the clipboard and this PR supports this scenario.
> Auto store token after pasting

- packages/blob-reader/helper.js
Markdown code snippets are not represented in git. Therefore linking does not work and we return `undefined` as a path. This caused issues with relative imports in readmes which then failed the GitHub API call.
> Do not link relative imports in code snippets

- packages/core/app.js
- packages/helper-normalise-resolver-results/index.js
- packages/helper-normalise-resolver-results/test.js
Under certain circumstances relative file paths in a diff view were resolved using the ping resolver instead of the GitHub Tree API.
> Ensure GitHub Tree API is used for relative files

- packages/helper-settings/components/input.js
The settings dialog in Microsoft Edge is slightly smaller which cut off the input field. This PR adjust the input field width.
> Adjust responsive design for MS Edge

- packages/helper-settings/SettingsForm.js
The UX when adding a GitHub token felt very clunky. There seems to be a timing issue between `linkState` and `validateToken`. This isn't a proper fix, but it does the job.
> Improve adding token UX

- e2e/fixtures/.github/CODEOWNERS
- packages/core/load-plugins.js
- packages/core/package.json
- packages/helper-insert-link/index.js
- packages/plugin-github-codeowners/index.js
- packages/plugin-github-codeowners/package.json
Fixes #550 
The following patterns will be ignored
- `*`
- `**/foo`
- `foo/*.bar`
- `foo/*/*.bar`
- `# /foo`
all other patterns should work.
> Add support for GitHub CODEOWNERS

- e2e/fixtures/dotnet/SdkProject.csproj
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- packages/plugin-dot-net/index.js
This builds on #785 so the `Sdk` attribute is also handled now.
> Add project sdk support for .net

- e2e/fixtures/javascript/index.js
- e2e/fixtures/javascript/package.json
- packages/plugin-npm-manifest/index.js
Dependencies defined with version `latest` are not resolved in package.json files. 
https://github.com/microsoft/TypeScript/blob/ab1458ac55df6a32edc0df861705bcd186a58b61/package.json#L64
> version with value "latest" are not linked in package.json

- e2e/fixtures/javascript/package.json
- packages/helper-insert-link/__tests__/__snapshots__/get-position.js.snap
- packages/helper-insert-link/__tests__/get-position.js
- packages/helper-insert-link/get-position.js
- packages/helper-insert-link/index.js
- packages/helper-regex-builder/__tests__/index.js
- packages/helper-regex-builder/index.js
Referencing dependencies using github shorthands or as git urls worked in the past, but seems to be broken since quite a while. 
```json
"dependencies": {
"express": "expressjs/express",
"mocha": "mochajs/mocha#v7.0.0",
"angular": "git@github.com:angular/angular.git"
}
```
> Fix URLs as dependencies in package.json

- e2e/fixtures/javascript/package.json
- packages/plugin-npm-manifest/index.js
- packages/resolver-github-shorthand/__tests__/index.js
- packages/resolver-github-shorthand/index.js
This PR adds support for `github:user/repo` format in a package.json file
```json
"dependencies": {
"express": "github:expressjs/express"
}
```
Solves #790
> Add support for github: in package.json

- packages/plugin-dot-net-core/__tests__/index.js
- packages/plugin-dot-net/__tests__/index.js
- packages/resolver-nuget/index.js
- packages/resolver-nuget/package.json
By default OctoLinker validates external URLs via https://octolinker-api.now.sh/ to ensure the linked URL is valid and reachable. This obviously slows down the startup since OctoLinker needs to wait for the API response. There is a special resolver called `resolver-trusted-url` which allows you to opt-out from this behaviour. This is useful for documentation pages or registry urls where you can ensure the right url.
> Bypass OctoLinker API for nuget urls

- e2e/fixtures/dotnet/dotnet-tools.json
- packages/core/load-plugins.js
- packages/core/package.json
- packages/helper-regex-builder/__tests__/index.js
- packages/helper-regex-builder/index.js
- packages/plugin-dot-net-core/package.json
- packages/plugin-dot-net-global-tools/__tests__/index.js
- packages/plugin-dot-net-global-tools/index.js
- packages/plugin-dot-net-global-tools/package.json
- packages/plugin-dot-net/package.json
**Sample files**
- https://github.com/dotnet/runtime/blob/ac68cdeeea2abbff988448fe7915f2bcf5ee3cfd/.config/dotnet-tools.json
- https://github.com/dotnet/roslyn/blob/e3a461796d3cb4917367af73778d2ab34f6812e9/dotnet-tools.json
The changes to the regex builder are needed to allow turning off the `g` flag because some tools have commands of the same name, such as in the second link, and both instances of `dotnet-format` were being linkified.
> Add support for .net global tool configs

- packages/helper-github-api/fetch-tree.js
- packages/helper-insert-link/index.js
- packages/helper-octolinker-api/index.js
This should get rid of the warning annotations that keep showing up on each PR.
> Disable no-console warnings

- .github/workflows/ci.yml
- .github/workflows/release.yml
There were changes in how the checkout is done between v1 and v2. This shouldn't effect the ci workflow but I'm not sure about the release workflow.
https://github.com/actions/checkout/releases/tag/v2.0.0
- Improved fetch performance
- The default behavior now fetches only the commit being checked-out
- Script authenticated git commands
- Persists the input `token` in the local git config
- Enables your scripts to run authenticated git commands
- Post-job cleanup removes the token
- Opt out by setting the input `persist-credentials: false`
- Creates a local branch
- No longer detached HEAD when checking out a branch
- A local branch is created with the corresponding upstream branch set
- Improved layout
- The input `path` is always relative to $GITHUB_WORKSPACE
- Aligns better with …
> Bump actions/checkout from v1 to v2

- e2e/fixtures/dotnet/sdk/Project.csproj
- packages/helper-grammar-regex-collection/index.js
An example of these can be seen here https://github.com/dotnet/aspnetcore/blob/f7b5aec5d7de6f782622a2dc40de74d7dedd0a91/src/Analyzers/Analyzers/test/Microsoft.AspNetCore.Analyzers.Test.csproj#L21-L33.
One of the dependencies being linked to in that example is https://www.nuget.org/packages/Microsoft.AspNetCore.Analyzer.Testing but the package doesn't exist. Do we need to add an entry for NuGet to https://github.com/OctoLinker/api/blob/master/src/registries/config.json?
> Add support for .net references

- e2e/diff-fixtures.json
- packages/core/loader.js
As raised in https://github.com/OctoLinker/OctoLinker/pull/785#issuecomment-580069754 some references are not linked in a diff view. It turned out that the removing of duplicates was causing this issue for certain matches. Original implemented to remove duplicates before calling the OctoLinker API, this cleanup was performed on all matches regardless their type. Only matches with type  `registry` and `ping` need this cleanup.
Examples:
- https://github.com/OctoLinker/OctoLinker/pull/785/files#diff-9222904f7ff80fd69544d107fbf18b0a
- https://github.com/facebook/jest/pull/9443/files#diff-a568cf5f01a8aa0032eca9f2692ba0b0R8
> Deduplicate matches for OctoLinker API only

- e2e/automated.test.js
- e2e/diff-fixtures.json
- packages/blob-reader/helper.js
Related to #821 
PR review comments with a code snippet (not to be confused with code suggestions) caused linking of the entire blob to fail. OctoLinkers DOM parsing missed the blob because the code snippet  took precedence over the blob DOM element.
> Fix PR reviews comment snippets

- packages/blob-reader/fixtures/github.com/pull/comments.html
- packages/blob-reader/helper.js
- packages/blob-reader/index.js
Fixes #821 
After some back and forth how to fix this best, I went with the simplest solution which means no linking when using the "suggest changes" features. In an ideal situation, we were able to separate and create a virtual blob just for the "suggested changes" code. I thought about it multiple times, but since this requires a bigger refactoring I went with the simplest solution which turns off linking for this box.
> Do not pare suggested code changes block

- packages/ratelimit-notification/__tests__/__snapshots__/messages.js.snap
- packages/ratelimit-notification/messages.js
Small improvement to point people to settings page in case they don't need private repo support
> Add hint to disable OctoLinker for private repos

- packages/plugin-nodejs-relative-path/index.js
- packages/plugin-nodejs-relative-path/package.json
There are a few places which are doing something very similar to the relative file resolver that we already have. #796 lists all of them, but apart from the NodeJS plugin, all the others are slightly different so let's start easy 😉
> Use relative resolver for nodejs plugin

- packages/core/notification.js
- packages/helper-settings/index.js
- packages/user-interface/index.js
Recently, I was talking to friend and he made me aware of an issue with the update notification. The update notification appears immediately whenever the extension updates. If a user navigates to another GitHub page or performs a page reload, the notification is gone forever. With this change we persist the notification state until a user interaction happens (either close or following the link)
> Persist update notification on reload

- packages/user-interface/index.js
- packages/user-interface/style.css
Qhat you see is not what you get! Applies to `event.target` as well 😉 
The click handler condition to persist the state of the notification was never met, because `event.target` was pointing to the icon `<svg>` instead of the `<button>` 🤦‍♂ 
https://github.com/OctoLinker/OctoLinker/blob/bed093fbf5d20d2494cfae2514c8bf60c80e6fe7/packages/core/notification.js#L11-L14
> Keep update notification closed when using close icon

- packages/core/loader.js
@xt0rted pointed me to this amazing idea which allows us to show a sneak preview of the linked repository using hover cards. I hope you like it as much as I do.
> Add hover card to preview to repositories

- assets/manifest.json
While working on #870 I added https://api.github.com to the wrong array in the manifest.json file. It needs to be part of the permissions field.
This mistake is really annoying and leads to another permission ask when updating the extension next time 😞
> Declare api.github.com as permission

- .github/workflows/ci.yml
Thanks to https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/
> Drop CI env variable from GHA Workflow

- packages/core/app.js
- packages/core/stats.js
This is an idea that I have had for some time. I want to show the value of OctoLinker by tracking how often OctoLinker is being used to gain insights. With the recently added hover card #869 we need to monitor hover events as well.
- The date of the first track event.
- A counter which increases by one whenever you click or hover over a OctoLinker link
This information will be used at some point to show you a message like this. `Since April 28th, 2020 you clicked on 124 links provided by OctoLinker.
We store data on on your computer in the browser's local storage only. No sync, no upload, we respect your privacy!
> Track personal usage of OctoLinker

- e2e/fixtures/.github/workflows/ci.yml
- e2e/generate-fixtures-json.js
- packages/plugin-github-actions/index.js
This builds on the existing support and adds links for local actions in the current repo, as well as actions that have sub actions which are located in a sub folder for the given action.
I had to hard code `master` for one of the urls because we don't have branch/commit information for it. What we could do is adjust the regex to capture the `@v1` value and use that. That should be a tag or commit which both work in the url and would be more accurate.
**Local**
https://github.com/github/codeql-action/blob/a0d60d5d9e3126a00bed89fd89cc89b7e52a56f2/.github/workflows/codeql.yml#L24-L28
**Sub folders**
https://github.com/twbs/bootstrap/blob/5faf41eb4837491fa8193910c5816efadb4dbc5a/.github/workflows/codeql.yml#L22-L25
> More GitHub actions support

- packages/user-interface/index.js
I noticed this while trying to test #975. I never got the popup until I adjusted this check.
Unfortunately there's no classes on the page that indicate if this is a private repo now that they've moved everything to utility classes. I confirmed the site is only served in English (for now) so checking for the label's text like this should be ok.
**Current HTML**
```html
<h1 class=" d-flex flex-wrap flex-items-center break-word f3 text-normal">
<svg class="octicon octicon-repo-forked text-gray" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M5 3.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm0 2.122a2.25 2.25 0 10-1.5 0v.878A2.25 2.25 0 005.75 8.5h1.5v2.128a2.251 2.251 0 101.5 0V8.5h1.5a2.25 2.25 0 002.25-2.25v-.878a2.25 2.25 0 10-1.5 …
```
> Fix broken private repo check

- e2e/fixtures/ruby/mystic-wind.rb
- e2e/generate-fixtures-json.js
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- packages/helper-insert-link/index.js
- packages/plugin-ruby/index.js
Issue #773 
* [`require_relative "channel_prefix"`](https://github.com/rails/rails/blob/f891a8d7d43eb3e66f65f5d74217133b713967c4/actioncable/test/subscription_adapter/redis_test.rb#L5)
* [`require "action_cable/subscription_adapter/redis"`](https://github.com/rails/rails/blob/f891a8d7d43eb3e66f65f5d74217133b713967c4/actioncable/test/subscription_adapter/redis_test.rb#L7)
* Some require_relatives were resolving to a RubyGems page instead of a relative file such as [`require_relative "common"`](https://github.com/rails/rails/blob/f891a8d7d43eb3e66f65f5d74217133b713967c4/actioncable/test/subscription_adapter/redis_test.rb#L5)
> Ruby require_relative fixes

- e2e/fixtures/css/main.css
- e2e/fixtures/less/main.less
- packages/plugin-less/index.js
[![](https://github.com/OctoLinker/OctoLinker/workflows/Node%20CI/badge.svg?branch=extensionless-less-imports)](https://github.com/OctoLinker/OctoLinker/pull/1034/checks) [![Pull Request Badge](https://badgen.net/badge/Generated%20by/Pull%20Request%20Badge/purple)](https://pullrequestbadge.com/?rel=badge)
Found this while setting up tests for #905. This functionality is mentioned in the docs at http://lesscss.org/features/#import-atrules-feature.
The only issue with this change is once the `url()` support in #905 is added we end up adding an extra lookup since images & fonts don't end in `.less`. I could add an extra check for common image/font extensions if you'd like, or maybe move that to `plugin-css-url`.
> Support extensionless less imports

- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
[![](https://github.com/OctoLinker/OctoLinker/workflows/Node%20CI/badge.svg?branch=css-url-imports)](https://github.com/OctoLinker/OctoLinker/pull/1036/checks) [![Pull Request Badge](https://badgen.net/badge/Generated%20by/Pull%20Request%20Badge/purple)](https://pullrequestbadge.com/?rel=badge)
This is another thing I found while working on #905. I was trying to exclude things like `url("https://...")` so we didn't do needless lookups and it turns out the same thing happens with css imports. I'm sure this exists for LESS and SASS as well but didn't dig into those yet.
I'm wondering if there's a better way to handle this. Any ideas?
You can see an example of this here:
- https://github.com/meninaveneno/ROCK-STORY/blob/f0c8d332517c70161420da49feeaf7c786d7fb40/ROCKing.css
> Exclude urls from css imports

- e2e/fixtures/php/foo.php
- packages/blob-reader/fixtures/github.com/issue/code.html
- packages/core/load-plugins.js
- packages/core/package.json
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- packages/plugin-php/__tests__/index.js
- packages/plugin-php/index.js
- packages/plugin-php/package.json
[![](https://github.com/OctoLinker/OctoLinker/workflows/Node%20CI/badge.svg?branch=phpdocs)](https://github.com/OctoLinker/OctoLinker/pull/1033/checks) [![Pull Request Badge](https://badgen.net/badge/Generated%20by/Pull%20Request%20Badge/purple)](https://pullrequestbadge.com/?rel=badge)
Support for PHP is limited in OctoLinker, and besides making dependencies clickable in a `composer.json` we don't do any other linking. However, providing better PHP support is on my list for quite some time now. This PR links PHP core classes to the related php.net manual page
```php
<?php
use Closure; // => https://www.php.net/manual/en/class.closure.php
use Exception; // => https://www.php.net/manual/en/class.exception.php
use ArrayAccess; // => https://www.php.net/manual/en/class.arrayaccess.php
use …
```
> Add PHP manual support

- e2e/README.md
- e2e/automated.test.js
- e2e/fixtures/php/foo.php
- e2e/generate-fixtures-json.js
[![](https://github.com/OctoLinker/OctoLinker/workflows/Node%20CI/badge.svg?branch=e2e-annotation-not)](https://github.com/OctoLinker/OctoLinker/pull/1046/checks) [![Pull Request Badge](https://badgen.net/badge/Generated%20by/Pull%20Request%20Badge/purple)](https://pullrequestbadge.com/?rel=badge)
As discussed in https://github.com/OctoLinker/OctoLinker/pull/1033#discussion_r496966053 this PR introduce a NOT annotation 
```
// @OctoLinkerDoesNotResolve
require('ftp://foo.bar')
```
> Add e2e test NOT annotation

- CONTRIBUTING.md
- package.json
- packages/core/notification.js
- packages/core/package.json
- scripts/version.sh
[![](https://github.com/OctoLinker/OctoLinker/workflows/Node%20CI/badge.svg?branch=release-note)](https://github.com/OctoLinker/OctoLinker/pull/1050/checks) [![Pull Request Badge](https://badgen.net/badge/Generated%20by/Pull%20Request%20Badge/purple)](https://pullrequestbadge.com/?rel=badge)
This change ensures that a release description is added before performing a release using `npm version <patch|minor|major>`
> Ensure release note is updated

- e2e/automated.test.js
- e2e/generate-fixtures-json.js
[![](https://github.com/OctoLinker/OctoLinker/workflows/Node%20CI/badge.svg?branch=test-annotations)](https://github.com/OctoLinker/OctoLinker/pull/1063/checks) [![Pull Request Badge](https://badgen.net/badge/Generated%20by/Pull%20Request%20Badge/purple)](https://pullrequestbadge.com/?rel=badge)
I split this out of #1035 since it's not related to that piece of work.
I'm wondering if we should take a dependency on [actions/core](https://github.com/actions/toolkit/tree/main/packages/core) so we can use their [`issueCommand`](https://github.com/actions/toolkit/blob/main/packages/core/src/command.ts) function which handles building & escaping everything.
> Creating annotations for failed e2e tests

- packages/plugin-php/__tests__/index.js
- packages/plugin-php/index.js
The return value from a resolve needs to be an array as discussed here https://github.com/OctoLinker/OctoLinker/pull/1035#discussion_r500038960. This might be worth a patch release
> Fix return value of PHP plugin

- e2e/diff-fixtures.json
Following up on https://github.com/OctoLinker/OctoLinker/pull/1079#issuecomment-708201350 it seems like GitHub made some tweaks to the hash when linking to a specific line in a diff view.
> Update fixtures url to meet new url structure

- e2e/__snapshots__/automated.test.js.snap
- e2e/automated.test.js
This is another safety net to ensure the behaviour stays the same when refactoring code. This is needed because our custom annotation may does not cover all scenarios we have.
> Count total OctoLinker links while running e2e tests

- packages/user-interface/style.css
As outlined in https://github.com/ovity/octotree/issues/997, Octotree is hiding the toast notification that we introduced recently. Usually I would like to avoid such tweaks, but since Octotree is a widely used extension it's worth a fix in my opinion.
> Adjust toast position for Octotree

- packages/core/stats.js
- packages/helper-settings/SettingsForm.js
- packages/helper-settings/components/index.js
- packages/helper-settings/components/stats.js
- packages/helper-settings/index.js
- packages/helper-settings/style.css
Since https://github.com/OctoLinker/OctoLinker/pull/917 we track the usage of OctoLinker by increasing a counter whenever a user follows a link. The data are stored in the users browser using the Storage API. This PR makes this statiscs accesibale by adding a new section to the settings page.
Reviewer note: [ignore whitespace in diff using this link](https://github.com/OctoLinker/OctoLinker/pull/1129/files?w=1)
> Show usage statistics on setttings page

- e2e/__snapshots__/automated.test.js.snap
- e2e/fixtures/php/foo.php
- packages/helper-insert-link/index.js
- packages/helper-settings/SettingsForm.js
- packages/helper-settings/index.js
- packages/plugin-php/__tests__/index.js
- packages/plugin-php/index.js
- packages/plugin-php/mapping.js
- packages/plugin-php/package.json
Add feature preview to support to link `use` statements from the following projects:
- Symfony
- Laravel
- Doctrine
- CakePHP
- PHPUnit
To enable the feature, go to the extension settings page and enable the `Better PHP support` checkbox
> Add laravel support

- packages/helper-insert-link/__tests__/__snapshots__/index.js.snap
- packages/helper-insert-link/__tests__/index.js
- packages/helper-insert-link/index.js
As described in #1165 and #1166, the printed source code gets rewritten in certain circumstances. This happens if a matching keyword appears on both side of the import statement. By taking the matching group index into account the correct element is wrapped with a octolinker link.
> Wrap element based on the matching group offset

- .github/workflows/ci.yml
Follows: https://github.com/OctoLinker/OctoLinker/pull/1167#issuecomment-757384115
From the log:
```
Artifact artifact was downloaded to /Users/runner/work/OctoLinker/OctoLinker/dist/artifact
9
```
> Fix Safari CI build

- assets/manifest.json
They are the defaults already https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts
> Drop unnecessary details from manifest.json

- webpack.config.js
After completing  the webpack 5 migration, I've noticed that [webpack-extension-reloader](https://github.com/rubenspgcavalcante/webpack-extension-reloader) is not working anymore. The auto reloading is super important when working on OctoLinker (at least for me). The plugin itself hasn't been update for a year and is therefore not 100% compatible with webpack 5 anymore. Disabling the sourcemap creation is fixing the problem. 
```
(node:4628) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:4628) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using …
```
> Disable sourcemaps to get webpack-extension-reloader working

- packages/core/app.js
The issue reported in https://github.com/OctoLinker/OctoLinker/issues/942#issuecomment-976689694 is a result of how Firefox is treating the `window.requestIdleCallback` assignment. In Chrome this works fine, but in Firefox any call to it results in the error:
>TypeError: 'requestIdleCallback' called on an object that does not implement interface Window.
I had the same results in v94 and v96.
Another option is to remove the conditional check and [shim the function](https://developers.google.com/web/updates/2015/08/using-requestidlecallback#checking_for_requestidlecallback) at the top of the file with:
```js
window.requestIdleCallback =
window.requestIdleCallback ||
function (cb) {
const start = Date.now();
return setTimeout(() => {
cb({
didTimeout: false,
timeRemaining: () => Math.max(0, …
```
> Bind window object to requestIdleCallback assignment

- e2e/fixtures/solidity/foo.sol
- packages/helper-grammar-regex-collection/index.js
- packages/plugin-solidity/index.js
This PR improve the matching of Solidity files by using the JS regex.
Now matching also:
```solidity
import {YourContract} from "./import.sol";
```
> Solidity: improve path matching

- e2e/fixtures/javascript/index.js
- packages/plugin-javascript/__tests__/index.js
- packages/plugin-javascript/index.js
Looks to be supported in:
- `v16.0.0`, `v14.18.0` (ESM import and CommonJS require())
- `v14.13.1`, `v12.20.0` (only ESM import)
- In TypeScript with the latest versions of `@types/node`
Fixes #1466
> Support built-in packages with `node:` prefix

- packages/plugin-github-actions/__tests__/index.js
- packages/plugin-github-actions/index.js
[Workflow templates](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization) need to exist in a repo named `.github` and a folder named `workflow-templates`. If there's a better way to check for this I can change it, but this seemed like the easiest way. Since this is based on the repo & folder name I couldn't put an e2e test for it, but the unit tests should be sufficient I think.
Example files:
- https://github.com/xt0rted/.github/blob/dfc99168e4dd2f9f827eab0a9e58ce7ed3a1f0f2/workflow-templates/dependabot-auto-merge.yml#L11
- https://github.com/primer/.github/tree/main/workflow-templates
> Add support for action workflow templates

- e2e/fixtures/docker/Dockerfile
- packages/plugin-docker/__tests__/index.js
- packages/plugin-docker/index.js
- packages/plugin-github-actions/index.js
Fixes #1455 
This change enables any docker registry, whereas before OctoLinker assumed all images hosted on docker hub.
> Add support for any docker registry

- e2e/automated.test.js
Neither of these objects are awaitable according to code analysis and since the `diff-fixtures.json` file is committed to source control there's no need to disable the `import/no-unresolved` rule for it.
> Remove unnecessary awaits and convert to es module

- e2e/fixtures/.github/workflows/ci.yml
- packages/helper-grammar-regex-collection/index.js
- packages/helper-grammar-regex-collection/test.js
- packages/plugin-github-actions/__tests__/index.js
- packages/plugin-github-actions/index.js
This adjusts GitHub Actions links so if they include a tag/sha we link directly to that instead of the default branch. I figured since most actions are pinned to a version it'd make more sense to link to that instead of the default branch. I'm not sure if we want to do this or not, I'm fine with it either way.
> Link github actions to their pinned version

- .github/workflows/ci.yml
This will cancel an in-progress workflow if another instance of it starts.
https://docs.github.com/en/actions/using-jobs/using-concurrency
> Add concurrency settings

- e2e/fixtures/go/foo.go
- packages/helper-grammar-regex-collection/go.js
- packages/plugin-go/__tests__/index.js
- packages/plugin-go/index.js
The change in url caused the e2e tests to start to fail.
The other urls are technically wrong because `https://golang.org/pkg/context` redirects to `https://pkg.go.dev/context` but updating them causes the tests to fail. This is probably because of https://github.com/OctoLinker/OctoLinker/blob/4a54d31577f21659e33d0fa1cdfff00dc9d02ad3/packages/plugin-go/index.js#L53
> Update resolve url

- .github/workflows/ci.yml
- .github/workflows/release.yml
This change forces color output in the build log for things like jest's test results making it easier to find failing tests. There's a [known issue](https://github.com/actions/setup-node/issues/317) with `actions/setup-node` where when this is set the cache feature fails, so it has to be disabled for that step.
> Set FORCE_COLOR

- packages/blob-reader/helper.js
The [new code experience](https://github.blog/changelog/2022-11-09-introducing-an-all-new-code-search-and-code-browsing-experience/) (currently in beta)  introduced a few DOM changes that OctoLinker wasn't able to cope with. Luckily just a few changes are necessary to make OctoLinker work again.
> fix: Make OctoLinker work with the new code experience

- .github/dependabot.yml
According to support this should stop the commit message prefixes we recently started getting applied to dependabot PRs.
> Set an explicit commit message prefix

- .github/dependabot.yml
I talked to support about the commit message prefixes that started being used here (happened in one of my repos too) and they said the way to prevent it to by setting the `commit-message` property in the dependabot config.
> Add explicit commit message prefix

- packages/helper-insert-link/__tests__/__snapshots__/index.js.snap
- packages/helper-insert-link/index.js
This resolves the issue mentioned in https://github.com/OctoLinker/OctoLinker/issues/1695#issuecomment-1312817951 which should be backwards compatible with the old site. I'm not sure if there's a better way to do this, but based on what their code's doing this attribute is what stops the `pl-token` class from being added which is where the hover style comes from. They set it to `true` so I figured `false` made more sense in this context.
> Prevent GitHub's code navigation styling on our links
